// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockExchangeService.proto

package com.consorsbank.module.tapi.grpc.stock;

public interface StockExchangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.consorsbank.module.tapi.grpc.StockExchangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * Access token
   * </pre>
   *
   * <code>string access_token = 1;</code>
   */
  java.lang.String getAccessToken();
  /**
   * <pre>
   **
   * Access token
   * </pre>
   *
   * <code>string access_token = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <pre>
   **
   * Stock exchange
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.StockExchange stock_exchange = 2;</code>
   */
  boolean hasStockExchange();
  /**
   * <pre>
   **
   * Stock exchange
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.StockExchange stock_exchange = 2;</code>
   */
  com.consorsbank.module.tapi.grpc.stock.StockExchange getStockExchange();
  /**
   * <pre>
   **
   * Stock exchange
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.StockExchange stock_exchange = 2;</code>
   */
  com.consorsbank.module.tapi.grpc.stock.StockExchangeOrBuilder getStockExchangeOrBuilder();
}
