// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockExchangeService.proto

package com.consorsbank.module.tapi.grpc.stock;

public final class StockExchangeService {
  private StockExchangeService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_StockExchange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_StockExchange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_StockExchangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_StockExchangeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeDescriptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_StockExchangeDescriptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeDescription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_StockExchangeDescription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032StockExchangeService.proto\022 com.consor" +
      "sbank.module.tapi.grpc\032\014Common.proto\"+\n\r" +
      "StockExchange\022\n\n\002id\030\001 \001(\t\022\016\n\006issuer\030\002 \001(" +
      "\t\"u\n\024StockExchangeRequest\022\024\n\014access_toke" +
      "n\030\001 \001(\t\022G\n\016stock_exchange\030\002 \001(\0132/.com.co" +
      "nsorsbank.module.tapi.grpc.StockExchange" +
      "\"i\n\021StockExchangeInfo\022F\n\rstockExchange\030\001" +
      " \001(\0132/.com.consorsbank.module.tapi.grpc." +
      "StockExchange\022\014\n\004name\030\002 \001(\t\"\247\001\n\031StockExc" +
      "hangeDescriptions\022Q\n\024stock_exchange_info" +
      "s\030\001 \003(\01323.com.consorsbank.module.tapi.gr" +
      "pc.StockExchangeInfo\0227\n\005error\030\350\007 \001(\0132\'.c" +
      "om.consorsbank.module.tapi.grpc.Error\"\245\001" +
      "\n\030StockExchangeDescription\022P\n\023stock_exch" +
      "ange_info\030\001 \001(\01323.com.consorsbank.module" +
      ".tapi.grpc.StockExchangeInfo\0227\n\005error\030\350\007" +
      " \001(\0132\'.com.consorsbank.module.tapi.grpc." +
      "ErrorB*\n&com.consorsbank.module.tapi.grp" +
      "c.stockP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.consorsbank.module.tapi.grpc.common.Common.getDescriptor(),
        }, assigner);
    internal_static_com_consorsbank_module_tapi_grpc_StockExchange_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_consorsbank_module_tapi_grpc_StockExchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_StockExchange_descriptor,
        new java.lang.String[] { "Id", "Issuer", });
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_StockExchangeRequest_descriptor,
        new java.lang.String[] { "AccessToken", "StockExchange", });
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_StockExchangeInfo_descriptor,
        new java.lang.String[] { "StockExchange", "Name", });
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeDescriptions_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeDescriptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_StockExchangeDescriptions_descriptor,
        new java.lang.String[] { "StockExchangeInfos", "Error", });
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeDescription_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_consorsbank_module_tapi_grpc_StockExchangeDescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_StockExchangeDescription_descriptor,
        new java.lang.String[] { "StockExchangeInfo", "Error", });
    com.consorsbank.module.tapi.grpc.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
