// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package com.consorsbank.module.tapi.grpc.account;

public interface TradingAccountTransactionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.consorsbank.module.tapi.grpc.TradingAccountTransactions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * Trading account
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  boolean hasAccount();
  /**
   * <pre>
   **
   * Trading account
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  com.consorsbank.module.tapi.grpc.account.TradingAccount getAccount();
  /**
   * <pre>
   **
   * Trading account
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder getAccountOrBuilder();

  /**
   * <pre>
   **
   * List of transactions
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccountTransactions.Transaction transactions = 2;</code>
   */
  java.util.List<com.consorsbank.module.tapi.grpc.account.TradingAccountTransactions.Transaction> 
      getTransactionsList();
  /**
   * <pre>
   **
   * List of transactions
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccountTransactions.Transaction transactions = 2;</code>
   */
  com.consorsbank.module.tapi.grpc.account.TradingAccountTransactions.Transaction getTransactions(int index);
  /**
   * <pre>
   **
   * List of transactions
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccountTransactions.Transaction transactions = 2;</code>
   */
  int getTransactionsCount();
  /**
   * <pre>
   **
   * List of transactions
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccountTransactions.Transaction transactions = 2;</code>
   */
  java.util.List<? extends com.consorsbank.module.tapi.grpc.account.TradingAccountTransactions.TransactionOrBuilder> 
      getTransactionsOrBuilderList();
  /**
   * <pre>
   **
   * List of transactions
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccountTransactions.Transaction transactions = 2;</code>
   */
  com.consorsbank.module.tapi.grpc.account.TradingAccountTransactions.TransactionOrBuilder getTransactionsOrBuilder(
      int index);

  /**
   * <pre>
   **
   * Error information if happened
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  boolean hasError();
  /**
   * <pre>
   **
   * Error information if happened
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  com.consorsbank.module.tapi.grpc.common.Error getError();
  /**
   * <pre>
   **
   * Error information if happened
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder getErrorOrBuilder();
}
