// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package com.consorsbank.module.tapi.grpc.account;

public interface TradingAccountInformationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.consorsbank.module.tapi.grpc.TradingAccountInformation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * Trading account
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  boolean hasAccount();
  /**
   * <pre>
   **
   * Trading account
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  com.consorsbank.module.tapi.grpc.account.TradingAccount getAccount();
  /**
   * <pre>
   **
   * Trading account
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder getAccountOrBuilder();

  /**
   * <pre>
   **
   * Account balance
   * </pre>
   *
   * <code>double balance = 2;</code>
   */
  double getBalance();

  /**
   * <pre>
   **
   * Credit limit information
   * </pre>
   *
   * <code>double credit_limit = 3;</code>
   */
  double getCreditLimit();

  /**
   * <pre>
   **
   * Buying power
   * </pre>
   *
   * <code>double buying_power = 4;</code>
   */
  double getBuyingPower();

  /**
   * <pre>
   **
   * Credit limit intraday information, #pro# only
   * </pre>
   *
   * <code>double credit_limit_intraday = 9;</code>
   */
  double getCreditLimitIntraday();

  /**
   * <pre>
   **
   * Buyng power intraday, #pro# only
   * </pre>
   *
   * <code>double buying_power_intraday = 10;</code>
   */
  double getBuyingPowerIntraday();

  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  boolean hasError();
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  com.consorsbank.module.tapi.grpc.common.Error getError();
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder getErrorOrBuilder();
}
