// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package com.consorsbank.module.tapi.grpc.account;

/**
 * <pre>
 **
 * TradingAccounts contains account information 
 * from current session
 * </pre>
 *
 * Protobuf type {@code com.consorsbank.module.tapi.grpc.TradingAccounts}
 */
public  final class TradingAccounts extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.consorsbank.module.tapi.grpc.TradingAccounts)
    TradingAccountsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TradingAccounts.newBuilder() to construct.
  private TradingAccounts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TradingAccounts() {
    accounts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TradingAccounts(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              accounts_ = new java.util.ArrayList<com.consorsbank.module.tapi.grpc.account.TradingAccount>();
              mutable_bitField0_ |= 0x00000001;
            }
            accounts_.add(
                input.readMessage(com.consorsbank.module.tapi.grpc.account.TradingAccount.parser(), extensionRegistry));
            break;
          }
          case 8002: {
            com.consorsbank.module.tapi.grpc.common.Error.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.consorsbank.module.tapi.grpc.common.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        accounts_ = java.util.Collections.unmodifiableList(accounts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.consorsbank.module.tapi.grpc.account.AccountService.internal_static_com_consorsbank_module_tapi_grpc_TradingAccounts_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.consorsbank.module.tapi.grpc.account.AccountService.internal_static_com_consorsbank_module_tapi_grpc_TradingAccounts_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.consorsbank.module.tapi.grpc.account.TradingAccounts.class, com.consorsbank.module.tapi.grpc.account.TradingAccounts.Builder.class);
  }

  private int bitField0_;
  public static final int ACCOUNTS_FIELD_NUMBER = 1;
  private java.util.List<com.consorsbank.module.tapi.grpc.account.TradingAccount> accounts_;
  /**
   * <pre>
   **
   * List of trading accounts
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
   */
  public java.util.List<com.consorsbank.module.tapi.grpc.account.TradingAccount> getAccountsList() {
    return accounts_;
  }
  /**
   * <pre>
   **
   * List of trading accounts
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
   */
  public java.util.List<? extends com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder> 
      getAccountsOrBuilderList() {
    return accounts_;
  }
  /**
   * <pre>
   **
   * List of trading accounts
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
   */
  public int getAccountsCount() {
    return accounts_.size();
  }
  /**
   * <pre>
   **
   * List of trading accounts
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
   */
  public com.consorsbank.module.tapi.grpc.account.TradingAccount getAccounts(int index) {
    return accounts_.get(index);
  }
  /**
   * <pre>
   **
   * List of trading accounts
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
   */
  public com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder getAccountsOrBuilder(
      int index) {
    return accounts_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 1000;
  private com.consorsbank.module.tapi.grpc.common.Error error_;
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  public com.consorsbank.module.tapi.grpc.common.Error getError() {
    return error_ == null ? com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
  }
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  public com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < accounts_.size(); i++) {
      output.writeMessage(1, accounts_.get(i));
    }
    if (error_ != null) {
      output.writeMessage(1000, getError());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < accounts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, accounts_.get(i));
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1000, getError());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.consorsbank.module.tapi.grpc.account.TradingAccounts)) {
      return super.equals(obj);
    }
    com.consorsbank.module.tapi.grpc.account.TradingAccounts other = (com.consorsbank.module.tapi.grpc.account.TradingAccounts) obj;

    boolean result = true;
    result = result && getAccountsList()
        .equals(other.getAccountsList());
    result = result && (hasError() == other.hasError());
    if (hasError()) {
      result = result && getError()
          .equals(other.getError());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAccountsCount() > 0) {
      hash = (37 * hash) + ACCOUNTS_FIELD_NUMBER;
      hash = (53 * hash) + getAccountsList().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.consorsbank.module.tapi.grpc.account.TradingAccounts prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * TradingAccounts contains account information 
   * from current session
   * </pre>
   *
   * Protobuf type {@code com.consorsbank.module.tapi.grpc.TradingAccounts}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.consorsbank.module.tapi.grpc.TradingAccounts)
      com.consorsbank.module.tapi.grpc.account.TradingAccountsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.consorsbank.module.tapi.grpc.account.AccountService.internal_static_com_consorsbank_module_tapi_grpc_TradingAccounts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.consorsbank.module.tapi.grpc.account.AccountService.internal_static_com_consorsbank_module_tapi_grpc_TradingAccounts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.consorsbank.module.tapi.grpc.account.TradingAccounts.class, com.consorsbank.module.tapi.grpc.account.TradingAccounts.Builder.class);
    }

    // Construct using com.consorsbank.module.tapi.grpc.account.TradingAccounts.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAccountsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (accountsBuilder_ == null) {
        accounts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        accountsBuilder_.clear();
      }
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.consorsbank.module.tapi.grpc.account.AccountService.internal_static_com_consorsbank_module_tapi_grpc_TradingAccounts_descriptor;
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.account.TradingAccounts getDefaultInstanceForType() {
      return com.consorsbank.module.tapi.grpc.account.TradingAccounts.getDefaultInstance();
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.account.TradingAccounts build() {
      com.consorsbank.module.tapi.grpc.account.TradingAccounts result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.account.TradingAccounts buildPartial() {
      com.consorsbank.module.tapi.grpc.account.TradingAccounts result = new com.consorsbank.module.tapi.grpc.account.TradingAccounts(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (accountsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          accounts_ = java.util.Collections.unmodifiableList(accounts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.accounts_ = accounts_;
      } else {
        result.accounts_ = accountsBuilder_.build();
      }
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.consorsbank.module.tapi.grpc.account.TradingAccounts) {
        return mergeFrom((com.consorsbank.module.tapi.grpc.account.TradingAccounts)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.consorsbank.module.tapi.grpc.account.TradingAccounts other) {
      if (other == com.consorsbank.module.tapi.grpc.account.TradingAccounts.getDefaultInstance()) return this;
      if (accountsBuilder_ == null) {
        if (!other.accounts_.isEmpty()) {
          if (accounts_.isEmpty()) {
            accounts_ = other.accounts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAccountsIsMutable();
            accounts_.addAll(other.accounts_);
          }
          onChanged();
        }
      } else {
        if (!other.accounts_.isEmpty()) {
          if (accountsBuilder_.isEmpty()) {
            accountsBuilder_.dispose();
            accountsBuilder_ = null;
            accounts_ = other.accounts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            accountsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAccountsFieldBuilder() : null;
          } else {
            accountsBuilder_.addAllMessages(other.accounts_);
          }
        }
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.consorsbank.module.tapi.grpc.account.TradingAccounts parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.consorsbank.module.tapi.grpc.account.TradingAccounts) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.consorsbank.module.tapi.grpc.account.TradingAccount> accounts_ =
      java.util.Collections.emptyList();
    private void ensureAccountsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        accounts_ = new java.util.ArrayList<com.consorsbank.module.tapi.grpc.account.TradingAccount>(accounts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.account.TradingAccount, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder, com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder> accountsBuilder_;

    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public java.util.List<com.consorsbank.module.tapi.grpc.account.TradingAccount> getAccountsList() {
      if (accountsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(accounts_);
      } else {
        return accountsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public int getAccountsCount() {
      if (accountsBuilder_ == null) {
        return accounts_.size();
      } else {
        return accountsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccount getAccounts(int index) {
      if (accountsBuilder_ == null) {
        return accounts_.get(index);
      } else {
        return accountsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public Builder setAccounts(
        int index, com.consorsbank.module.tapi.grpc.account.TradingAccount value) {
      if (accountsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountsIsMutable();
        accounts_.set(index, value);
        onChanged();
      } else {
        accountsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public Builder setAccounts(
        int index, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder builderForValue) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.set(index, builderForValue.build());
        onChanged();
      } else {
        accountsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public Builder addAccounts(com.consorsbank.module.tapi.grpc.account.TradingAccount value) {
      if (accountsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountsIsMutable();
        accounts_.add(value);
        onChanged();
      } else {
        accountsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public Builder addAccounts(
        int index, com.consorsbank.module.tapi.grpc.account.TradingAccount value) {
      if (accountsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAccountsIsMutable();
        accounts_.add(index, value);
        onChanged();
      } else {
        accountsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public Builder addAccounts(
        com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder builderForValue) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.add(builderForValue.build());
        onChanged();
      } else {
        accountsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public Builder addAccounts(
        int index, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder builderForValue) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.add(index, builderForValue.build());
        onChanged();
      } else {
        accountsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public Builder addAllAccounts(
        java.lang.Iterable<? extends com.consorsbank.module.tapi.grpc.account.TradingAccount> values) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, accounts_);
        onChanged();
      } else {
        accountsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public Builder clearAccounts() {
      if (accountsBuilder_ == null) {
        accounts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        accountsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public Builder removeAccounts(int index) {
      if (accountsBuilder_ == null) {
        ensureAccountsIsMutable();
        accounts_.remove(index);
        onChanged();
      } else {
        accountsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder getAccountsBuilder(
        int index) {
      return getAccountsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder getAccountsOrBuilder(
        int index) {
      if (accountsBuilder_ == null) {
        return accounts_.get(index);  } else {
        return accountsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public java.util.List<? extends com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder> 
         getAccountsOrBuilderList() {
      if (accountsBuilder_ != null) {
        return accountsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(accounts_);
      }
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder addAccountsBuilder() {
      return getAccountsFieldBuilder().addBuilder(
          com.consorsbank.module.tapi.grpc.account.TradingAccount.getDefaultInstance());
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder addAccountsBuilder(
        int index) {
      return getAccountsFieldBuilder().addBuilder(
          index, com.consorsbank.module.tapi.grpc.account.TradingAccount.getDefaultInstance());
    }
    /**
     * <pre>
     **
     * List of trading accounts
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.TradingAccount accounts = 1;</code>
     */
    public java.util.List<com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder> 
         getAccountsBuilderList() {
      return getAccountsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.account.TradingAccount, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder, com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder> 
        getAccountsFieldBuilder() {
      if (accountsBuilder_ == null) {
        accountsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.account.TradingAccount, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder, com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder>(
                accounts_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        accounts_ = null;
      }
      return accountsBuilder_;
    }

    private com.consorsbank.module.tapi.grpc.common.Error error_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder> errorBuilder_;
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder setError(com.consorsbank.module.tapi.grpc.common.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder setError(
        com.consorsbank.module.tapi.grpc.common.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder mergeError(com.consorsbank.module.tapi.grpc.common.Error value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.consorsbank.module.tapi.grpc.common.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.Error.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.consorsbank.module.tapi.grpc.TradingAccounts)
  }

  // @@protoc_insertion_point(class_scope:com.consorsbank.module.tapi.grpc.TradingAccounts)
  private static final com.consorsbank.module.tapi.grpc.account.TradingAccounts DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.consorsbank.module.tapi.grpc.account.TradingAccounts();
  }

  public static com.consorsbank.module.tapi.grpc.account.TradingAccounts getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TradingAccounts>
      PARSER = new com.google.protobuf.AbstractParser<TradingAccounts>() {
    @java.lang.Override
    public TradingAccounts parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TradingAccounts(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TradingAccounts> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TradingAccounts> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.consorsbank.module.tapi.grpc.account.TradingAccounts getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

