// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package com.consorsbank.module.tapi.grpc.account;

public interface TradingAccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.consorsbank.module.tapi.grpc.TradingAccount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * Account number
   * </pre>
   *
   * <code>string account_number = 1;</code>
   */
  java.lang.String getAccountNumber();
  /**
   * <pre>
   **
   * Account number
   * </pre>
   *
   * <code>string account_number = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountNumberBytes();

  /**
   * <pre>
   **
   * Depot number
   * </pre>
   *
   * <code>string depot_number = 2;</code>
   */
  java.lang.String getDepotNumber();
  /**
   * <pre>
   **
   * Depot number
   * </pre>
   *
   * <code>string depot_number = 2;</code>
   */
  com.google.protobuf.ByteString
      getDepotNumberBytes();

  /**
   * <pre>
   **
   * Name of the account owners
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   **
   * Name of the account owners
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   **
   *  If account is tradable then true or false otherwise
   * </pre>
   *
   * <code>bool tradable = 4;</code>
   */
  boolean getTradable();
}
