// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package com.consorsbank.module.tapi.grpc.security;

/**
 * <pre>
 **
 * Requests security information for security code
 * </pre>
 *
 * Protobuf type {@code com.consorsbank.module.tapi.grpc.SecurityInfoRequest}
 */
public  final class SecurityInfoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.consorsbank.module.tapi.grpc.SecurityInfoRequest)
    SecurityInfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SecurityInfoRequest.newBuilder() to construct.
  private SecurityInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SecurityInfoRequest() {
    accessToken_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SecurityInfoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accessToken_ = s;
            break;
          }
          case 18: {
            com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder subBuilder = null;
            if (securityCode_ != null) {
              subBuilder = securityCode_.toBuilder();
            }
            securityCode_ = input.readMessage(com.consorsbank.module.tapi.grpc.security.SecurityCode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(securityCode_);
              securityCode_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.consorsbank.module.tapi.grpc.security.SecurityService.internal_static_com_consorsbank_module_tapi_grpc_SecurityInfoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.consorsbank.module.tapi.grpc.security.SecurityService.internal_static_com_consorsbank_module_tapi_grpc_SecurityInfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest.class, com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest.Builder.class);
  }

  public static final int ACCESS_TOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object accessToken_;
  /**
   * <pre>
   **
   * Access token
   * </pre>
   *
   * <code>string access_token = 1;</code>
   */
  public java.lang.String getAccessToken() {
    java.lang.Object ref = accessToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accessToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * Access token
   * </pre>
   *
   * <code>string access_token = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAccessTokenBytes() {
    java.lang.Object ref = accessToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accessToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECURITY_CODE_FIELD_NUMBER = 2;
  private com.consorsbank.module.tapi.grpc.security.SecurityCode securityCode_;
  /**
   * <pre>
   **
   * Security code with security type (WKN, ISIN) 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
   */
  public boolean hasSecurityCode() {
    return securityCode_ != null;
  }
  /**
   * <pre>
   **
   * Security code with security type (WKN, ISIN) 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
   */
  public com.consorsbank.module.tapi.grpc.security.SecurityCode getSecurityCode() {
    return securityCode_ == null ? com.consorsbank.module.tapi.grpc.security.SecurityCode.getDefaultInstance() : securityCode_;
  }
  /**
   * <pre>
   **
   * Security code with security type (WKN, ISIN) 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
   */
  public com.consorsbank.module.tapi.grpc.security.SecurityCodeOrBuilder getSecurityCodeOrBuilder() {
    return getSecurityCode();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccessTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accessToken_);
    }
    if (securityCode_ != null) {
      output.writeMessage(2, getSecurityCode());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccessTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accessToken_);
    }
    if (securityCode_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSecurityCode());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest)) {
      return super.equals(obj);
    }
    com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest other = (com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest) obj;

    boolean result = true;
    result = result && getAccessToken()
        .equals(other.getAccessToken());
    result = result && (hasSecurityCode() == other.hasSecurityCode());
    if (hasSecurityCode()) {
      result = result && getSecurityCode()
          .equals(other.getSecurityCode());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getAccessToken().hashCode();
    if (hasSecurityCode()) {
      hash = (37 * hash) + SECURITY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityCode().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Requests security information for security code
   * </pre>
   *
   * Protobuf type {@code com.consorsbank.module.tapi.grpc.SecurityInfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.consorsbank.module.tapi.grpc.SecurityInfoRequest)
      com.consorsbank.module.tapi.grpc.security.SecurityInfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.consorsbank.module.tapi.grpc.security.SecurityService.internal_static_com_consorsbank_module_tapi_grpc_SecurityInfoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.consorsbank.module.tapi.grpc.security.SecurityService.internal_static_com_consorsbank_module_tapi_grpc_SecurityInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest.class, com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest.Builder.class);
    }

    // Construct using com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      accessToken_ = "";

      if (securityCodeBuilder_ == null) {
        securityCode_ = null;
      } else {
        securityCode_ = null;
        securityCodeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.consorsbank.module.tapi.grpc.security.SecurityService.internal_static_com_consorsbank_module_tapi_grpc_SecurityInfoRequest_descriptor;
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest getDefaultInstanceForType() {
      return com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest build() {
      com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest buildPartial() {
      com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest result = new com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest(this);
      result.accessToken_ = accessToken_;
      if (securityCodeBuilder_ == null) {
        result.securityCode_ = securityCode_;
      } else {
        result.securityCode_ = securityCodeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest) {
        return mergeFrom((com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest other) {
      if (other == com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest.getDefaultInstance()) return this;
      if (!other.getAccessToken().isEmpty()) {
        accessToken_ = other.accessToken_;
        onChanged();
      }
      if (other.hasSecurityCode()) {
        mergeSecurityCode(other.getSecurityCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object accessToken_ = "";
    /**
     * <pre>
     **
     * Access token
     * </pre>
     *
     * <code>string access_token = 1;</code>
     */
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * Access token
     * </pre>
     *
     * <code>string access_token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * Access token
     * </pre>
     *
     * <code>string access_token = 1;</code>
     */
    public Builder setAccessToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accessToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * Access token
     * </pre>
     *
     * <code>string access_token = 1;</code>
     */
    public Builder clearAccessToken() {
      
      accessToken_ = getDefaultInstance().getAccessToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * Access token
     * </pre>
     *
     * <code>string access_token = 1;</code>
     */
    public Builder setAccessTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accessToken_ = value;
      onChanged();
      return this;
    }

    private com.consorsbank.module.tapi.grpc.security.SecurityCode securityCode_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.security.SecurityCode, com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder, com.consorsbank.module.tapi.grpc.security.SecurityCodeOrBuilder> securityCodeBuilder_;
    /**
     * <pre>
     **
     * Security code with security type (WKN, ISIN) 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
     */
    public boolean hasSecurityCode() {
      return securityCodeBuilder_ != null || securityCode_ != null;
    }
    /**
     * <pre>
     **
     * Security code with security type (WKN, ISIN) 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.security.SecurityCode getSecurityCode() {
      if (securityCodeBuilder_ == null) {
        return securityCode_ == null ? com.consorsbank.module.tapi.grpc.security.SecurityCode.getDefaultInstance() : securityCode_;
      } else {
        return securityCodeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * Security code with security type (WKN, ISIN) 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
     */
    public Builder setSecurityCode(com.consorsbank.module.tapi.grpc.security.SecurityCode value) {
      if (securityCodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        securityCode_ = value;
        onChanged();
      } else {
        securityCodeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Security code with security type (WKN, ISIN) 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
     */
    public Builder setSecurityCode(
        com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder builderForValue) {
      if (securityCodeBuilder_ == null) {
        securityCode_ = builderForValue.build();
        onChanged();
      } else {
        securityCodeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * Security code with security type (WKN, ISIN) 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
     */
    public Builder mergeSecurityCode(com.consorsbank.module.tapi.grpc.security.SecurityCode value) {
      if (securityCodeBuilder_ == null) {
        if (securityCode_ != null) {
          securityCode_ =
            com.consorsbank.module.tapi.grpc.security.SecurityCode.newBuilder(securityCode_).mergeFrom(value).buildPartial();
        } else {
          securityCode_ = value;
        }
        onChanged();
      } else {
        securityCodeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Security code with security type (WKN, ISIN) 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
     */
    public Builder clearSecurityCode() {
      if (securityCodeBuilder_ == null) {
        securityCode_ = null;
        onChanged();
      } else {
        securityCode_ = null;
        securityCodeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * Security code with security type (WKN, ISIN) 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder getSecurityCodeBuilder() {
      
      onChanged();
      return getSecurityCodeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * Security code with security type (WKN, ISIN) 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.security.SecurityCodeOrBuilder getSecurityCodeOrBuilder() {
      if (securityCodeBuilder_ != null) {
        return securityCodeBuilder_.getMessageOrBuilder();
      } else {
        return securityCode_ == null ?
            com.consorsbank.module.tapi.grpc.security.SecurityCode.getDefaultInstance() : securityCode_;
      }
    }
    /**
     * <pre>
     **
     * Security code with security type (WKN, ISIN) 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.security.SecurityCode, com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder, com.consorsbank.module.tapi.grpc.security.SecurityCodeOrBuilder> 
        getSecurityCodeFieldBuilder() {
      if (securityCodeBuilder_ == null) {
        securityCodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.security.SecurityCode, com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder, com.consorsbank.module.tapi.grpc.security.SecurityCodeOrBuilder>(
                getSecurityCode(),
                getParentForChildren(),
                isClean());
        securityCode_ = null;
      }
      return securityCodeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.consorsbank.module.tapi.grpc.SecurityInfoRequest)
  }

  // @@protoc_insertion_point(class_scope:com.consorsbank.module.tapi.grpc.SecurityInfoRequest)
  private static final com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest();
  }

  public static com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SecurityInfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<SecurityInfoRequest>() {
    @java.lang.Override
    public SecurityInfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SecurityInfoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SecurityInfoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SecurityInfoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.consorsbank.module.tapi.grpc.security.SecurityInfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

