// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package com.consorsbank.module.tapi.grpc.order;

public interface AcceptQuoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.consorsbank.module.tapi.grpc.AcceptQuoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * Access token
   * </pre>
   *
   * <code>string access_token = 1;</code>
   */
  java.lang.String getAccessToken();
  /**
   * <pre>
   **
   * Access token
   * </pre>
   *
   * <code>string access_token = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <pre>
   ** 
   * Trading account number 
   * </pre>
   *
   * <code>string account_number = 2;</code>
   */
  java.lang.String getAccountNumber();
  /**
   * <pre>
   ** 
   * Trading account number 
   * </pre>
   *
   * <code>string account_number = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccountNumberBytes();

  /**
   * <pre>
   ** 
   * Security code with stock exchange 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityWithStockExchange security_with_stockexchange = 3;</code>
   */
  boolean hasSecurityWithStockexchange();
  /**
   * <pre>
   ** 
   * Security code with stock exchange 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityWithStockExchange security_with_stockexchange = 3;</code>
   */
  com.consorsbank.module.tapi.grpc.security.SecurityWithStockExchange getSecurityWithStockexchange();
  /**
   * <pre>
   ** 
   * Security code with stock exchange 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityWithStockExchange security_with_stockexchange = 3;</code>
   */
  com.consorsbank.module.tapi.grpc.security.SecurityWithStockExchangeOrBuilder getSecurityWithStockexchangeOrBuilder();

  /**
   * <pre>
   **
   * Order type. It should be relevant to the requested GetQuoteRequest 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 4;</code>
   */
  int getOrderTypeValue();
  /**
   * <pre>
   **
   * Order type. It should be relevant to the requested GetQuoteRequest 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 4;</code>
   */
  com.consorsbank.module.tapi.grpc.trading.OrderType getOrderType();

  /**
   * <pre>
   **
   * Amount, It should be relevant to the requested GetQuoteRequest 
   * </pre>
   *
   * <code>double amount = 5;</code>
   */
  double getAmount();

  /**
   * <pre>
   **
   * Limit 
   * </pre>
   *
   * <code>double limit = 6;</code>
   */
  double getLimit();

  /**
   * <pre>
   **
   * Quote reference from GetQuoteRequest 
   * </pre>
   *
   * <code>string quote_reference = 7;</code>
   */
  java.lang.String getQuoteReference();
  /**
   * <pre>
   **
   * Quote reference from GetQuoteRequest 
   * </pre>
   *
   * <code>string quote_reference = 7;</code>
   */
  com.google.protobuf.ByteString
      getQuoteReferenceBytes();

  /**
   * <pre>
   **
   * Validation flag. 
   * If value is WITHOUT_VALIDATION then backend system sends order actions directly to the market. + 
   * If value is VALIDATE_ONLY then backend system doesn't send order actions to the market, but validate order parameters. +
   * If value is VALIDATE_WITH_TOTAL_COSTS then order will validated by backend system and request total costs for the order. +
   * If value is VALIDATE_WITH_DETAIL_COSTS then order will validated by backend system and request detail costs for the order. +
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Validation validation = 8;</code>
   */
  int getValidationValue();
  /**
   * <pre>
   **
   * Validation flag. 
   * If value is WITHOUT_VALIDATION then backend system sends order actions directly to the market. + 
   * If value is VALIDATE_ONLY then backend system doesn't send order actions to the market, but validate order parameters. +
   * If value is VALIDATE_WITH_TOTAL_COSTS then order will validated by backend system and request total costs for the order. +
   * If value is VALIDATE_WITH_DETAIL_COSTS then order will validated by backend system and request detail costs for the order. +
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Validation validation = 8;</code>
   */
  com.consorsbank.module.tapi.grpc.order.Validation getValidation();

  /**
   * <pre>
   **
   * Risk class override flag. If true then allowes override user risk class 
   * </pre>
   *
   * <code>bool risk_class_override = 9;</code>
   */
  boolean getRiskClassOverride();

  /**
   * <pre>
   **
   * Target market override flag. If true then allowes override target market 
   * </pre>
   *
   * <code>bool target_market_override = 10;</code>
   */
  boolean getTargetMarketOverride();

  /**
   * <pre>
   **
   * Tax non trasparent override flag. If true then allowes override tax intransparesity 
   * </pre>
   *
   * <code>bool tax_nontransparent_override = 11;</code>
   */
  boolean getTaxNontransparentOverride();

  /**
   * <pre>
   **
   * Accept additinal fees flag. If true then allowes accept non transparent fees 
   * </pre>
   *
   * <code>bool accept_additional_fees = 12;</code>
   */
  boolean getAcceptAdditionalFees();
}
