// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package com.consorsbank.module.tapi.grpc.order;

public final class OrderService {
  private OrderService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_AddOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_AddOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_OrderReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_OrderReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_CategoryCost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_CategoryCost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_AggregatedCosts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_AggregatedCosts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_DetailCost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_DetailCost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_ChangeOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_ChangeOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_CancelOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_CancelOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_ActivateOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_ActivateOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_DeactivateOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_DeactivateOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_AcceptQuoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_AcceptQuoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_QuoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_QuoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_QuoteReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_QuoteReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_QuoteEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_QuoteEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_Orders_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_Orders_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022OrderService.proto\022 com.consorsbank.mo" +
      "dule.tapi.grpc\032\014Common.proto\032\025SecuritySe" +
      "rvice.proto\032\032StockExchangeService.proto\032" +
      "\024AccountService.proto\032\022TradingTypes.prot" +
      "o\"\257\007\n\005Order\022`\n\033security_with_stockexchan" +
      "ge\030\001 \001(\0132;.com.consorsbank.module.tapi.g" +
      "rpc.SecurityWithStockExchange\022?\n\norder_t" +
      "ype\030\002 \001(\0162+.com.consorsbank.module.tapi." +
      "grpc.OrderType\022\024\n\014order_number\030\003 \001(\t\022\016\n\006" +
      "amount\030\004 \001(\001\022A\n\013order_model\030\005 \001(\0162,.com." +
      "consorsbank.module.tapi.grpc.OrderModel\022" +
      "K\n\020order_supplement\030\006 \001(\01621.com.consorsb" +
      "ank.module.tapi.grpc.OrderSupplement\022G\n\016" +
      "cash_quotation\030\007 \001(\0162/.com.consorsbank.m" +
      "odule.tapi.grpc.CashQuotation\022\027\n\017execute" +
      "d_amount\030\010 \001(\001\022C\n\014order_status\030\t \001(\0162-.c" +
      "om.consorsbank.module.tapi.grpc.OrderSta" +
      "tus\022E\n\020status_timestamp\030\n \001(\0132+.com.cons" +
      "orsbank.module.tapi.grpc.Timestamp\022=\n\rva" +
      "lidity_date\030\013 \001(\0132&.com.consorsbank.modu" +
      "le.tapi.grpc.Date\022\r\n\005limit\030\014 \001(\001\022\014\n\004stop" +
      "\030\r \001(\001\022\022\n\nstop_limit\030\016 \001(\001\022\031\n\021trailing_d" +
      "istance\030\017 \001(\001\022M\n\021trailing_notation\030\020 \001(\016" +
      "22.com.consorsbank.module.tapi.grpc.Trai" +
      "lingNotation\022 \n\030trailing_limit_tolerance" +
      "\030\021 \001(\001\022\031\n\021dripping_quantity\030\022 \001(\001\022\034\n\024tra" +
      "ding_partner_name\030\023 \001(\t\022\027\n\017execution_quo" +
      "te\030\024 \001(\001\022\021\n\tunique_id\030\025 \001(\t\"\366\007\n\017AddOrder" +
      "Request\022\024\n\014access_token\030\001 \001(\t\022\026\n\016account" +
      "_number\030\002 \001(\t\022`\n\033security_with_stockexch" +
      "ange\030\003 \001(\0132;.com.consorsbank.module.tapi" +
      ".grpc.SecurityWithStockExchange\022?\n\norder" +
      "_type\030\004 \001(\0162+.com.consorsbank.module.tap" +
      "i.grpc.OrderType\022\016\n\006amount\030\005 \001(\001\022A\n\013orde" +
      "r_model\030\006 \001(\0162,.com.consorsbank.module.t" +
      "api.grpc.OrderModel\022K\n\020order_supplement\030" +
      "\007 \001(\01621.com.consorsbank.module.tapi.grpc" +
      ".OrderSupplement\022G\n\016cash_quotation\030\010 \001(\016" +
      "2/.com.consorsbank.module.tapi.grpc.Cash" +
      "Quotation\022=\n\rvalidity_date\030\t \001(\0132&.com.c" +
      "onsorsbank.module.tapi.grpc.Date\022\r\n\005limi" +
      "t\030\n \001(\001\022\014\n\004stop\030\013 \001(\001\022\022\n\nstop_limit\030\014 \001(" +
      "\001\022\031\n\021trailing_distance\030\r \001(\001\022M\n\021trailing" +
      "_notation\030\016 \001(\01622.com.consorsbank.module" +
      ".tapi.grpc.TrailingNotation\022 \n\030trailing_" +
      "limit_tolerance\030\017 \001(\001\022\031\n\021dripping_quanti" +
      "ty\030\020 \001(\001\022\023\n\013position_id\030\021 \001(\t\022@\n\nvalidat" +
      "ion\030\022 \001(\0162,.com.consorsbank.module.tapi." +
      "grpc.Validation\022\033\n\023risk_class_override\030\023" +
      " \001(\010\022\036\n\026target_market_override\030\024 \001(\010\022#\n\033" +
      "tax_nontransparent_override\030\025 \001(\010\022\036\n\026acc" +
      "ept_additional_fees\030\026 \001(\010\022\'\n\037closed_real" +
      "estate_fond_override\030\027 \001(\010\022\020\n\010inactive\030\030" +
      " \001(\010\"\203\002\n\nOrderReply\022A\n\007account\030\001 \001(\01320.c" +
      "om.consorsbank.module.tapi.grpc.TradingA" +
      "ccount\0226\n\005order\030\002 \001(\0132\'.com.consorsbank." +
      "module.tapi.grpc.Order\022A\n\013order_costs\030\003 " +
      "\001(\0132,.com.consorsbank.module.tapi.grpc.O" +
      "rderCosts\0227\n\005error\030\350\007 \001(\0132\'.com.consorsb" +
      "ank.module.tapi.grpc.Error\"\325\n\n\nOrderCost" +
      "s\022\035\n\025estimated_total_costs\030\001 \001(\001\022\017\n\007cost" +
      "_id\030\002 \001(\t\022R\n\017categorie_costs\030\003 \003(\01329.com" +
      ".consorsbank.module.tapi.grpc.OrderCosts" +
      ".CategoryCost\022V\n\020aggregated_costs\030\004 \001(\0132" +
      "<.com.consorsbank.module.tapi.grpc.Order" +
      "Costs.AggregatedCosts\032\324\001\n\014CategoryCost\022\023" +
      "\n\013category_id\030\001 \001(\t\022\026\n\016category_label\030\002 " +
      "\001(\t\022\032\n\022total_sum_absolute\030\003 \001(\001\022\032\n\022total" +
      "_sum_relative\030\004 \001(\001\022\020\n\010currency\030\005 \001(\t\022M\n" +
      "\014detail_costs\030\006 \003(\01327.com.consorsbank.mo" +
      "dule.tapi.grpc.OrderCosts.DetailCost\032\204\006\n" +
      "\017AggregatedCosts\022\031\n\021in_costs_absolute\030\001 " +
      "\001(\001\022\031\n\021in_costs_relative\030\002 \001(\001\022\031\n\021in_cos" +
      "ts_currency\030\003 \001(\t\022\032\n\022out_costs_absolute\030" +
      "\004 \001(\001\022\032\n\022out_costs_relative\030\005 \001(\001\022\032\n\022out" +
      "_costs_currency\030\006 \001(\t\022!\n\031instrument_cost" +
      "s_absolute\030\007 \001(\001\022!\n\031instrument_costs_rel" +
      "ative\030\010 \001(\001\022!\n\031instrument_costs_currency" +
      "\030\t \001(\t\022\036\n\026service_costs_absolute\030\n \001(\001\022\036" +
      "\n\026service_costs_relative\030\013 \001(\001\022\036\n\026servic" +
      "e_costs_currency\030\014 \001(\t\022\036\n\026subsidy_costs_" +
      "absolute\030\r \001(\001\022\036\n\026subsidy_costs_relative" +
      "\030\016 \001(\001\022\036\n\026subsidy_costs_currency\030\017 \001(\t\022\'" +
      "\n\037foreign_currency_costs_absolute\030\020 \001(\001\022" +
      "\'\n\037foreign_currency_costs_relative\030\021 \001(\001" +
      "\022\'\n\037foreign_currency_costs_currency\030\022 \001(" +
      "\t\022#\n\033performance_impact_absolute\030\023 \001(\001\022#" +
      "\n\033performance_impact_relative\030\024 \001(\001\022#\n\033p" +
      "erformance_impact_currency\030\025 \001(\t\022\027\n\017expe" +
      "cted_amount\030\026 \001(\001\022 \n\030expected_amount_cur" +
      "rency\030\027 \001(\t\032\214\001\n\nDetailCost\022\021\n\tdetail_id\030" +
      "\001 \001(\t\022\024\n\014detail_label\030\002 \001(\t\022\026\n\016value_abs" +
      "olute\030\003 \001(\001\022\026\n\016value_relative\030\004 \001(\001\022\020\n\010c" +
      "urrency\030\005 \001(\t\022\023\n\013detail_type\030\006 \001(\t\"\202\004\n\022C" +
      "hangeOrderRequest\022\024\n\014access_token\030\001 \001(\t\022" +
      "\026\n\016account_number\030\002 \001(\t\022\024\n\014order_number\030" +
      "\003 \001(\t\022\r\n\005limit\030\004 \001(\001\022\014\n\004stop\030\005 \001(\001\022\022\n\nst" +
      "op_limit\030\006 \001(\001\022\016\n\006amount\030\007 \001(\001\022=\n\rvalidi" +
      "ty_date\030\010 \001(\0132&.com.consorsbank.module.t" +
      "api.grpc.Date\022A\n\013order_model\030\t \001(\0162,.com" +
      ".consorsbank.module.tapi.grpc.OrderModel" +
      "\022K\n\020order_supplement\030\n \001(\01621.com.consors" +
      "bank.module.tapi.grpc.OrderSupplement\022\031\n" +
      "\021dripping_quantity\030\013 \001(\001\022@\n\nvalidation\030\014" +
      " \001(\0162,.com.consorsbank.module.tapi.grpc." +
      "Validation\022\031\n\021trailing_distance\030\r \001(\001\022 \n" +
      "\030trailing_limit_tolerance\030\016 \001(\001\"\232\001\n\022Canc" +
      "elOrderRequest\022\024\n\014access_token\030\001 \001(\t\022\026\n\016" +
      "account_number\030\002 \001(\t\022\024\n\014order_number\030\003 \001" +
      "(\t\022@\n\nvalidation\030\004 \001(\0162,.com.consorsbank" +
      ".module.tapi.grpc.Validation\"\234\001\n\024Activat" +
      "eOrderRequest\022\024\n\014access_token\030\001 \001(\t\022\026\n\016a" +
      "ccount_number\030\002 \001(\t\022\024\n\014order_number\030\003 \001(" +
      "\t\022@\n\nvalidation\030\004 \001(\0162,.com.consorsbank." +
      "module.tapi.grpc.Validation\"\236\001\n\026Deactiva" +
      "teOrderRequest\022\024\n\014access_token\030\001 \001(\t\022\026\n\016" +
      "account_number\030\002 \001(\t\022\024\n\014order_number\030\003 \001" +
      "(\t\022@\n\nvalidation\030\004 \001(\0162,.com.consorsbank" +
      ".module.tapi.grpc.Validation\"\341\003\n\022AcceptQ" +
      "uoteRequest\022\024\n\014access_token\030\001 \001(\t\022\026\n\016acc" +
      "ount_number\030\002 \001(\t\022`\n\033security_with_stock" +
      "exchange\030\003 \001(\0132;.com.consorsbank.module." +
      "tapi.grpc.SecurityWithStockExchange\022?\n\no" +
      "rder_type\030\004 \001(\0162+.com.consorsbank.module" +
      ".tapi.grpc.OrderType\022\016\n\006amount\030\005 \001(\001\022\r\n\005" +
      "limit\030\006 \001(\001\022\027\n\017quote_reference\030\007 \001(\t\022@\n\n" +
      "validation\030\010 \001(\0162,.com.consorsbank.modul" +
      "e.tapi.grpc.Validation\022\033\n\023risk_class_ove" +
      "rride\030\t \001(\010\022\036\n\026target_market_override\030\n " +
      "\001(\010\022#\n\033tax_nontransparent_override\030\013 \001(\010" +
      "\022\036\n\026accept_additional_fees\030\014 \001(\010\"\206\002\n\014Quo" +
      "teRequest\022\024\n\014access_token\030\001 \001(\t\022E\n\rsecur" +
      "ity_code\030\002 \001(\0132..com.consorsbank.module." +
      "tapi.grpc.SecurityCode\022?\n\norder_type\030\003 \001" +
      "(\0162+.com.consorsbank.module.tapi.grpc.Or" +
      "derType\022\016\n\006amount\030\004 \001(\001\022H\n\017stock_exchang" +
      "es\030\005 \003(\0132/.com.consorsbank.module.tapi.g" +
      "rpc.StockExchange\"\222\002\n\nQuoteReply\022E\n\rsecu" +
      "rity_code\030\001 \001(\0132..com.consorsbank.module" +
      ".tapi.grpc.SecurityCode\022?\n\norder_type\030\002 " +
      "\001(\0162+.com.consorsbank.module.tapi.grpc.O" +
      "rderType\022C\n\rprice_entries\030\003 \003(\0132,.com.co" +
      "nsorsbank.module.tapi.grpc.QuoteEntry\0227\n" +
      "\005error\030\350\007 \001(\0132\'.com.consorsbank.module.t" +
      "api.grpc.Error\"\263\003\n\nQuoteEntry\022G\n\016stock_e" +
      "xchange\030\001 \001(\0132/.com.consorsbank.module.t" +
      "api.grpc.StockExchange\022\021\n\tbuy_price\030\002 \001(" +
      "\001\022\022\n\nbuy_volume\030\003 \001(\001\022\022\n\nsell_price\030\004 \001(" +
      "\001\022\023\n\013sell_volume\030\005 \001(\001\022\022\n\nlast_price\030\006 \001" +
      "(\001\022\023\n\013last_volume\030\007 \001(\001\022>\n\tlast_time\030\010 \001" +
      "(\0132+.com.consorsbank.module.tapi.grpc.Ti" +
      "mestamp\022\020\n\010currency\030\t \001(\t\022\027\n\017quote_refer" +
      "ence\030\n \001(\t\022?\n\norder_type\030\013 \001(\0162+.com.con" +
      "sorsbank.module.tapi.grpc.OrderType\0227\n\005e" +
      "rror\030\350\007 \001(\0132\'.com.consorsbank.module.tap" +
      "i.grpc.Error\"\275\001\n\006Orders\022A\n\007account\030\001 \001(\013" +
      "20.com.consorsbank.module.tapi.grpc.Trad" +
      "ingAccount\0227\n\006orders\030\002 \003(\0132\'.com.consors" +
      "bank.module.tapi.grpc.Order\0227\n\005error\030\250F " +
      "\001(\0132\'.com.consorsbank.module.tapi.grpc.E" +
      "rror*\366\001\n\013OrderStatus\022\023\n\017NO_ORDER_STATUS\020" +
      "\000\022\007\n\003NEW\020\001\022\010\n\004OPEN\020\002\022\014\n\010EXECUTED\020\003\022\026\n\022PA" +
      "RTIALLY_EXECUTED\020\004\022\014\n\010CANCELED\020\005\022\023\n\017CANC" +
      "ELED_FORCED\020\006\022\022\n\016CANCELED_NOTED\020\007\022\024\n\020CAN" +
      "CELED_TIMEOUT\020\010\022\013\n\007CHANGED\020\t\022\021\n\rCHANGED_" +
      "NOTED\020\n\022\014\n\010INACTIVE\020\013\022\022\n\016INACTIVE_NOTED\020" +
      "\014\022\n\n\006STORNO\020\r*\214\001\n\nValidation\022\026\n\022WITHOUT_" +
      "VALIDATION\020\000\022\021\n\rVALIDATE_ONLY\020\001\022\035\n\031VALID" +
      "ATE_WITH_TOTAL_COSTS\020\002\022\036\n\032VALIDATE_WITH_" +
      "DETAIL_COSTS\020\003\022\024\n\020TOTAL_COSTS_ONLY\020\004B*\n&" +
      "com.consorsbank.module.tapi.grpc.orderP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.consorsbank.module.tapi.grpc.common.Common.getDescriptor(),
          com.consorsbank.module.tapi.grpc.security.SecurityService.getDescriptor(),
          com.consorsbank.module.tapi.grpc.stock.StockExchangeService.getDescriptor(),
          com.consorsbank.module.tapi.grpc.account.AccountService.getDescriptor(),
          com.consorsbank.module.tapi.grpc.trading.TradingTypes.getDescriptor(),
        }, assigner);
    internal_static_com_consorsbank_module_tapi_grpc_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_consorsbank_module_tapi_grpc_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_Order_descriptor,
        new java.lang.String[] { "SecurityWithStockexchange", "OrderType", "OrderNumber", "Amount", "OrderModel", "OrderSupplement", "CashQuotation", "ExecutedAmount", "OrderStatus", "StatusTimestamp", "ValidityDate", "Limit", "Stop", "StopLimit", "TrailingDistance", "TrailingNotation", "TrailingLimitTolerance", "DrippingQuantity", "TradingPartnerName", "ExecutionQuote", "UniqueId", });
    internal_static_com_consorsbank_module_tapi_grpc_AddOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_consorsbank_module_tapi_grpc_AddOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_AddOrderRequest_descriptor,
        new java.lang.String[] { "AccessToken", "AccountNumber", "SecurityWithStockexchange", "OrderType", "Amount", "OrderModel", "OrderSupplement", "CashQuotation", "ValidityDate", "Limit", "Stop", "StopLimit", "TrailingDistance", "TrailingNotation", "TrailingLimitTolerance", "DrippingQuantity", "PositionId", "Validation", "RiskClassOverride", "TargetMarketOverride", "TaxNontransparentOverride", "AcceptAdditionalFees", "ClosedRealestateFondOverride", "Inactive", });
    internal_static_com_consorsbank_module_tapi_grpc_OrderReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_consorsbank_module_tapi_grpc_OrderReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_OrderReply_descriptor,
        new java.lang.String[] { "Account", "Order", "OrderCosts", "Error", });
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_descriptor,
        new java.lang.String[] { "EstimatedTotalCosts", "CostId", "CategorieCosts", "AggregatedCosts", });
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_CategoryCost_descriptor =
      internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_descriptor.getNestedTypes().get(0);
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_CategoryCost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_CategoryCost_descriptor,
        new java.lang.String[] { "CategoryId", "CategoryLabel", "TotalSumAbsolute", "TotalSumRelative", "Currency", "DetailCosts", });
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_AggregatedCosts_descriptor =
      internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_descriptor.getNestedTypes().get(1);
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_AggregatedCosts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_AggregatedCosts_descriptor,
        new java.lang.String[] { "InCostsAbsolute", "InCostsRelative", "InCostsCurrency", "OutCostsAbsolute", "OutCostsRelative", "OutCostsCurrency", "InstrumentCostsAbsolute", "InstrumentCostsRelative", "InstrumentCostsCurrency", "ServiceCostsAbsolute", "ServiceCostsRelative", "ServiceCostsCurrency", "SubsidyCostsAbsolute", "SubsidyCostsRelative", "SubsidyCostsCurrency", "ForeignCurrencyCostsAbsolute", "ForeignCurrencyCostsRelative", "ForeignCurrencyCostsCurrency", "PerformanceImpactAbsolute", "PerformanceImpactRelative", "PerformanceImpactCurrency", "ExpectedAmount", "ExpectedAmountCurrency", });
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_DetailCost_descriptor =
      internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_descriptor.getNestedTypes().get(2);
    internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_DetailCost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_OrderCosts_DetailCost_descriptor,
        new java.lang.String[] { "DetailId", "DetailLabel", "ValueAbsolute", "ValueRelative", "Currency", "DetailType", });
    internal_static_com_consorsbank_module_tapi_grpc_ChangeOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_consorsbank_module_tapi_grpc_ChangeOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_ChangeOrderRequest_descriptor,
        new java.lang.String[] { "AccessToken", "AccountNumber", "OrderNumber", "Limit", "Stop", "StopLimit", "Amount", "ValidityDate", "OrderModel", "OrderSupplement", "DrippingQuantity", "Validation", "TrailingDistance", "TrailingLimitTolerance", });
    internal_static_com_consorsbank_module_tapi_grpc_CancelOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_consorsbank_module_tapi_grpc_CancelOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_CancelOrderRequest_descriptor,
        new java.lang.String[] { "AccessToken", "AccountNumber", "OrderNumber", "Validation", });
    internal_static_com_consorsbank_module_tapi_grpc_ActivateOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_consorsbank_module_tapi_grpc_ActivateOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_ActivateOrderRequest_descriptor,
        new java.lang.String[] { "AccessToken", "AccountNumber", "OrderNumber", "Validation", });
    internal_static_com_consorsbank_module_tapi_grpc_DeactivateOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_consorsbank_module_tapi_grpc_DeactivateOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_DeactivateOrderRequest_descriptor,
        new java.lang.String[] { "AccessToken", "AccountNumber", "OrderNumber", "Validation", });
    internal_static_com_consorsbank_module_tapi_grpc_AcceptQuoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_consorsbank_module_tapi_grpc_AcceptQuoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_AcceptQuoteRequest_descriptor,
        new java.lang.String[] { "AccessToken", "AccountNumber", "SecurityWithStockexchange", "OrderType", "Amount", "Limit", "QuoteReference", "Validation", "RiskClassOverride", "TargetMarketOverride", "TaxNontransparentOverride", "AcceptAdditionalFees", });
    internal_static_com_consorsbank_module_tapi_grpc_QuoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_consorsbank_module_tapi_grpc_QuoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_QuoteRequest_descriptor,
        new java.lang.String[] { "AccessToken", "SecurityCode", "OrderType", "Amount", "StockExchanges", });
    internal_static_com_consorsbank_module_tapi_grpc_QuoteReply_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_consorsbank_module_tapi_grpc_QuoteReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_QuoteReply_descriptor,
        new java.lang.String[] { "SecurityCode", "OrderType", "PriceEntries", "Error", });
    internal_static_com_consorsbank_module_tapi_grpc_QuoteEntry_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_consorsbank_module_tapi_grpc_QuoteEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_QuoteEntry_descriptor,
        new java.lang.String[] { "StockExchange", "BuyPrice", "BuyVolume", "SellPrice", "SellVolume", "LastPrice", "LastVolume", "LastTime", "Currency", "QuoteReference", "OrderType", "Error", });
    internal_static_com_consorsbank_module_tapi_grpc_Orders_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_consorsbank_module_tapi_grpc_Orders_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_Orders_descriptor,
        new java.lang.String[] { "Account", "Orders", "Error", });
    com.consorsbank.module.tapi.grpc.common.Common.getDescriptor();
    com.consorsbank.module.tapi.grpc.security.SecurityService.getDescriptor();
    com.consorsbank.module.tapi.grpc.stock.StockExchangeService.getDescriptor();
    com.consorsbank.module.tapi.grpc.account.AccountService.getDescriptor();
    com.consorsbank.module.tapi.grpc.trading.TradingTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
