// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package com.consorsbank.module.tapi.grpc.order;

/**
 * <pre>
 **
 * Orders represent pushed information about orders from one trading accounts 
 * </pre>
 *
 * Protobuf type {@code com.consorsbank.module.tapi.grpc.Orders}
 */
public  final class Orders extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.consorsbank.module.tapi.grpc.Orders)
    OrdersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Orders.newBuilder() to construct.
  private Orders(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Orders() {
    orders_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Orders(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder subBuilder = null;
            if (account_ != null) {
              subBuilder = account_.toBuilder();
            }
            account_ = input.readMessage(com.consorsbank.module.tapi.grpc.account.TradingAccount.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(account_);
              account_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              orders_ = new java.util.ArrayList<com.consorsbank.module.tapi.grpc.order.Order>();
              mutable_bitField0_ |= 0x00000002;
            }
            orders_.add(
                input.readMessage(com.consorsbank.module.tapi.grpc.order.Order.parser(), extensionRegistry));
            break;
          }
          case 72002: {
            com.consorsbank.module.tapi.grpc.common.Error.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.consorsbank.module.tapi.grpc.common.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        orders_ = java.util.Collections.unmodifiableList(orders_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_Orders_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_Orders_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.consorsbank.module.tapi.grpc.order.Orders.class, com.consorsbank.module.tapi.grpc.order.Orders.Builder.class);
  }

  private int bitField0_;
  public static final int ACCOUNT_FIELD_NUMBER = 1;
  private com.consorsbank.module.tapi.grpc.account.TradingAccount account_;
  /**
   * <pre>
   ** Trading account 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  public boolean hasAccount() {
    return account_ != null;
  }
  /**
   * <pre>
   ** Trading account 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  public com.consorsbank.module.tapi.grpc.account.TradingAccount getAccount() {
    return account_ == null ? com.consorsbank.module.tapi.grpc.account.TradingAccount.getDefaultInstance() : account_;
  }
  /**
   * <pre>
   ** Trading account 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  public com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder getAccountOrBuilder() {
    return getAccount();
  }

  public static final int ORDERS_FIELD_NUMBER = 2;
  private java.util.List<com.consorsbank.module.tapi.grpc.order.Order> orders_;
  /**
   * <pre>
   ** List of the orders 
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
   */
  public java.util.List<com.consorsbank.module.tapi.grpc.order.Order> getOrdersList() {
    return orders_;
  }
  /**
   * <pre>
   ** List of the orders 
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
   */
  public java.util.List<? extends com.consorsbank.module.tapi.grpc.order.OrderOrBuilder> 
      getOrdersOrBuilderList() {
    return orders_;
  }
  /**
   * <pre>
   ** List of the orders 
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
   */
  public int getOrdersCount() {
    return orders_.size();
  }
  /**
   * <pre>
   ** List of the orders 
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
   */
  public com.consorsbank.module.tapi.grpc.order.Order getOrders(int index) {
    return orders_.get(index);
  }
  /**
   * <pre>
   ** List of the orders 
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
   */
  public com.consorsbank.module.tapi.grpc.order.OrderOrBuilder getOrdersOrBuilder(
      int index) {
    return orders_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 9000;
  private com.consorsbank.module.tapi.grpc.common.Error error_;
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
   */
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
   */
  public com.consorsbank.module.tapi.grpc.common.Error getError() {
    return error_ == null ? com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
  }
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
   */
  public com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (account_ != null) {
      output.writeMessage(1, getAccount());
    }
    for (int i = 0; i < orders_.size(); i++) {
      output.writeMessage(2, orders_.get(i));
    }
    if (error_ != null) {
      output.writeMessage(9000, getError());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (account_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAccount());
    }
    for (int i = 0; i < orders_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, orders_.get(i));
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9000, getError());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.consorsbank.module.tapi.grpc.order.Orders)) {
      return super.equals(obj);
    }
    com.consorsbank.module.tapi.grpc.order.Orders other = (com.consorsbank.module.tapi.grpc.order.Orders) obj;

    boolean result = true;
    result = result && (hasAccount() == other.hasAccount());
    if (hasAccount()) {
      result = result && getAccount()
          .equals(other.getAccount());
    }
    result = result && getOrdersList()
        .equals(other.getOrdersList());
    result = result && (hasError() == other.hasError());
    if (hasError()) {
      result = result && getError()
          .equals(other.getError());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAccount()) {
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
    }
    if (getOrdersCount() > 0) {
      hash = (37 * hash) + ORDERS_FIELD_NUMBER;
      hash = (53 * hash) + getOrdersList().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.consorsbank.module.tapi.grpc.order.Orders parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.order.Orders parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.consorsbank.module.tapi.grpc.order.Orders prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Orders represent pushed information about orders from one trading accounts 
   * </pre>
   *
   * Protobuf type {@code com.consorsbank.module.tapi.grpc.Orders}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.consorsbank.module.tapi.grpc.Orders)
      com.consorsbank.module.tapi.grpc.order.OrdersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_Orders_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_Orders_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.consorsbank.module.tapi.grpc.order.Orders.class, com.consorsbank.module.tapi.grpc.order.Orders.Builder.class);
    }

    // Construct using com.consorsbank.module.tapi.grpc.order.Orders.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOrdersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (accountBuilder_ == null) {
        account_ = null;
      } else {
        account_ = null;
        accountBuilder_ = null;
      }
      if (ordersBuilder_ == null) {
        orders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        ordersBuilder_.clear();
      }
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_Orders_descriptor;
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.order.Orders getDefaultInstanceForType() {
      return com.consorsbank.module.tapi.grpc.order.Orders.getDefaultInstance();
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.order.Orders build() {
      com.consorsbank.module.tapi.grpc.order.Orders result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.order.Orders buildPartial() {
      com.consorsbank.module.tapi.grpc.order.Orders result = new com.consorsbank.module.tapi.grpc.order.Orders(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (accountBuilder_ == null) {
        result.account_ = account_;
      } else {
        result.account_ = accountBuilder_.build();
      }
      if (ordersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          orders_ = java.util.Collections.unmodifiableList(orders_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.orders_ = orders_;
      } else {
        result.orders_ = ordersBuilder_.build();
      }
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.consorsbank.module.tapi.grpc.order.Orders) {
        return mergeFrom((com.consorsbank.module.tapi.grpc.order.Orders)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.consorsbank.module.tapi.grpc.order.Orders other) {
      if (other == com.consorsbank.module.tapi.grpc.order.Orders.getDefaultInstance()) return this;
      if (other.hasAccount()) {
        mergeAccount(other.getAccount());
      }
      if (ordersBuilder_ == null) {
        if (!other.orders_.isEmpty()) {
          if (orders_.isEmpty()) {
            orders_ = other.orders_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureOrdersIsMutable();
            orders_.addAll(other.orders_);
          }
          onChanged();
        }
      } else {
        if (!other.orders_.isEmpty()) {
          if (ordersBuilder_.isEmpty()) {
            ordersBuilder_.dispose();
            ordersBuilder_ = null;
            orders_ = other.orders_;
            bitField0_ = (bitField0_ & ~0x00000002);
            ordersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrdersFieldBuilder() : null;
          } else {
            ordersBuilder_.addAllMessages(other.orders_);
          }
        }
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.consorsbank.module.tapi.grpc.order.Orders parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.consorsbank.module.tapi.grpc.order.Orders) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.consorsbank.module.tapi.grpc.account.TradingAccount account_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.account.TradingAccount, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder, com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder> accountBuilder_;
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public boolean hasAccount() {
      return accountBuilder_ != null || account_ != null;
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccount getAccount() {
      if (accountBuilder_ == null) {
        return account_ == null ? com.consorsbank.module.tapi.grpc.account.TradingAccount.getDefaultInstance() : account_;
      } else {
        return accountBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public Builder setAccount(com.consorsbank.module.tapi.grpc.account.TradingAccount value) {
      if (accountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        account_ = value;
        onChanged();
      } else {
        accountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public Builder setAccount(
        com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder builderForValue) {
      if (accountBuilder_ == null) {
        account_ = builderForValue.build();
        onChanged();
      } else {
        accountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public Builder mergeAccount(com.consorsbank.module.tapi.grpc.account.TradingAccount value) {
      if (accountBuilder_ == null) {
        if (account_ != null) {
          account_ =
            com.consorsbank.module.tapi.grpc.account.TradingAccount.newBuilder(account_).mergeFrom(value).buildPartial();
        } else {
          account_ = value;
        }
        onChanged();
      } else {
        accountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public Builder clearAccount() {
      if (accountBuilder_ == null) {
        account_ = null;
        onChanged();
      } else {
        account_ = null;
        accountBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder getAccountBuilder() {
      
      onChanged();
      return getAccountFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder getAccountOrBuilder() {
      if (accountBuilder_ != null) {
        return accountBuilder_.getMessageOrBuilder();
      } else {
        return account_ == null ?
            com.consorsbank.module.tapi.grpc.account.TradingAccount.getDefaultInstance() : account_;
      }
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.account.TradingAccount, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder, com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder> 
        getAccountFieldBuilder() {
      if (accountBuilder_ == null) {
        accountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.account.TradingAccount, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder, com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder>(
                getAccount(),
                getParentForChildren(),
                isClean());
        account_ = null;
      }
      return accountBuilder_;
    }

    private java.util.List<com.consorsbank.module.tapi.grpc.order.Order> orders_ =
      java.util.Collections.emptyList();
    private void ensureOrdersIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        orders_ = new java.util.ArrayList<com.consorsbank.module.tapi.grpc.order.Order>(orders_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.order.Order, com.consorsbank.module.tapi.grpc.order.Order.Builder, com.consorsbank.module.tapi.grpc.order.OrderOrBuilder> ordersBuilder_;

    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public java.util.List<com.consorsbank.module.tapi.grpc.order.Order> getOrdersList() {
      if (ordersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orders_);
      } else {
        return ordersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public int getOrdersCount() {
      if (ordersBuilder_ == null) {
        return orders_.size();
      } else {
        return ordersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.Order getOrders(int index) {
      if (ordersBuilder_ == null) {
        return orders_.get(index);
      } else {
        return ordersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public Builder setOrders(
        int index, com.consorsbank.module.tapi.grpc.order.Order value) {
      if (ordersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrdersIsMutable();
        orders_.set(index, value);
        onChanged();
      } else {
        ordersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public Builder setOrders(
        int index, com.consorsbank.module.tapi.grpc.order.Order.Builder builderForValue) {
      if (ordersBuilder_ == null) {
        ensureOrdersIsMutable();
        orders_.set(index, builderForValue.build());
        onChanged();
      } else {
        ordersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public Builder addOrders(com.consorsbank.module.tapi.grpc.order.Order value) {
      if (ordersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrdersIsMutable();
        orders_.add(value);
        onChanged();
      } else {
        ordersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public Builder addOrders(
        int index, com.consorsbank.module.tapi.grpc.order.Order value) {
      if (ordersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrdersIsMutable();
        orders_.add(index, value);
        onChanged();
      } else {
        ordersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public Builder addOrders(
        com.consorsbank.module.tapi.grpc.order.Order.Builder builderForValue) {
      if (ordersBuilder_ == null) {
        ensureOrdersIsMutable();
        orders_.add(builderForValue.build());
        onChanged();
      } else {
        ordersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public Builder addOrders(
        int index, com.consorsbank.module.tapi.grpc.order.Order.Builder builderForValue) {
      if (ordersBuilder_ == null) {
        ensureOrdersIsMutable();
        orders_.add(index, builderForValue.build());
        onChanged();
      } else {
        ordersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public Builder addAllOrders(
        java.lang.Iterable<? extends com.consorsbank.module.tapi.grpc.order.Order> values) {
      if (ordersBuilder_ == null) {
        ensureOrdersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orders_);
        onChanged();
      } else {
        ordersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public Builder clearOrders() {
      if (ordersBuilder_ == null) {
        orders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        ordersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public Builder removeOrders(int index) {
      if (ordersBuilder_ == null) {
        ensureOrdersIsMutable();
        orders_.remove(index);
        onChanged();
      } else {
        ordersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.Order.Builder getOrdersBuilder(
        int index) {
      return getOrdersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.OrderOrBuilder getOrdersOrBuilder(
        int index) {
      if (ordersBuilder_ == null) {
        return orders_.get(index);  } else {
        return ordersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public java.util.List<? extends com.consorsbank.module.tapi.grpc.order.OrderOrBuilder> 
         getOrdersOrBuilderList() {
      if (ordersBuilder_ != null) {
        return ordersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orders_);
      }
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.Order.Builder addOrdersBuilder() {
      return getOrdersFieldBuilder().addBuilder(
          com.consorsbank.module.tapi.grpc.order.Order.getDefaultInstance());
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.Order.Builder addOrdersBuilder(
        int index) {
      return getOrdersFieldBuilder().addBuilder(
          index, com.consorsbank.module.tapi.grpc.order.Order.getDefaultInstance());
    }
    /**
     * <pre>
     ** List of the orders 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.Order orders = 2;</code>
     */
    public java.util.List<com.consorsbank.module.tapi.grpc.order.Order.Builder> 
         getOrdersBuilderList() {
      return getOrdersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.order.Order, com.consorsbank.module.tapi.grpc.order.Order.Builder, com.consorsbank.module.tapi.grpc.order.OrderOrBuilder> 
        getOrdersFieldBuilder() {
      if (ordersBuilder_ == null) {
        ordersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.order.Order, com.consorsbank.module.tapi.grpc.order.Order.Builder, com.consorsbank.module.tapi.grpc.order.OrderOrBuilder>(
                orders_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        orders_ = null;
      }
      return ordersBuilder_;
    }

    private com.consorsbank.module.tapi.grpc.common.Error error_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder> errorBuilder_;
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
     */
    public Builder setError(com.consorsbank.module.tapi.grpc.common.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
     */
    public Builder setError(
        com.consorsbank.module.tapi.grpc.common.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
     */
    public Builder mergeError(com.consorsbank.module.tapi.grpc.common.Error value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.consorsbank.module.tapi.grpc.common.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.Error.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 9000;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.consorsbank.module.tapi.grpc.Orders)
  }

  // @@protoc_insertion_point(class_scope:com.consorsbank.module.tapi.grpc.Orders)
  private static final com.consorsbank.module.tapi.grpc.order.Orders DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.consorsbank.module.tapi.grpc.order.Orders();
  }

  public static com.consorsbank.module.tapi.grpc.order.Orders getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Orders>
      PARSER = new com.google.protobuf.AbstractParser<Orders>() {
    @java.lang.Override
    public Orders parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Orders(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Orders> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Orders> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.consorsbank.module.tapi.grpc.order.Orders getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

