// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package com.consorsbank.module.tapi.grpc.order;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.consorsbank.module.tapi.grpc.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   ** Security with stock echange 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityWithStockExchange security_with_stockexchange = 1;</code>
   */
  boolean hasSecurityWithStockexchange();
  /**
   * <pre>
   ** Security with stock echange 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityWithStockExchange security_with_stockexchange = 1;</code>
   */
  com.consorsbank.module.tapi.grpc.security.SecurityWithStockExchange getSecurityWithStockexchange();
  /**
   * <pre>
   ** Security with stock echange 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityWithStockExchange security_with_stockexchange = 1;</code>
   */
  com.consorsbank.module.tapi.grpc.security.SecurityWithStockExchangeOrBuilder getSecurityWithStockexchangeOrBuilder();

  /**
   * <pre>
   ** Order type 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 2;</code>
   */
  int getOrderTypeValue();
  /**
   * <pre>
   ** Order type 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 2;</code>
   */
  com.consorsbank.module.tapi.grpc.trading.OrderType getOrderType();

  /**
   * <pre>
   ** Order number 
   * </pre>
   *
   * <code>string order_number = 3;</code>
   */
  java.lang.String getOrderNumber();
  /**
   * <pre>
   ** Order number 
   * </pre>
   *
   * <code>string order_number = 3;</code>
   */
  com.google.protobuf.ByteString
      getOrderNumberBytes();

  /**
   * <pre>
   ** Amount of the securities 
   * </pre>
   *
   * <code>double amount = 4;</code>
   */
  double getAmount();

  /**
   * <pre>
   ** Order model 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderModel order_model = 5;</code>
   */
  int getOrderModelValue();
  /**
   * <pre>
   ** Order model 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderModel order_model = 5;</code>
   */
  com.consorsbank.module.tapi.grpc.trading.OrderModel getOrderModel();

  /**
   * <pre>
   ** Order supplement 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderSupplement order_supplement = 6;</code>
   */
  int getOrderSupplementValue();
  /**
   * <pre>
   ** Order supplement 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderSupplement order_supplement = 6;</code>
   */
  com.consorsbank.module.tapi.grpc.trading.OrderSupplement getOrderSupplement();

  /**
   * <pre>
   ** Cache quotation 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.CashQuotation cash_quotation = 7;</code>
   */
  int getCashQuotationValue();
  /**
   * <pre>
   ** Cache quotation 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.CashQuotation cash_quotation = 7;</code>
   */
  com.consorsbank.module.tapi.grpc.trading.CashQuotation getCashQuotation();

  /**
   * <pre>
   ** Executed amount
   * </pre>
   *
   * <code>double executed_amount = 8;</code>
   */
  double getExecutedAmount();

  /**
   * <pre>
   ** Order status 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderStatus order_status = 9;</code>
   */
  int getOrderStatusValue();
  /**
   * <pre>
   ** Order status 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderStatus order_status = 9;</code>
   */
  com.consorsbank.module.tapi.grpc.order.OrderStatus getOrderStatus();

  /**
   * <pre>
   ** Date and time of the order status 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Timestamp status_timestamp = 10;</code>
   */
  boolean hasStatusTimestamp();
  /**
   * <pre>
   ** Date and time of the order status 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Timestamp status_timestamp = 10;</code>
   */
  com.consorsbank.module.tapi.grpc.common.Timestamp getStatusTimestamp();
  /**
   * <pre>
   ** Date and time of the order status 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Timestamp status_timestamp = 10;</code>
   */
  com.consorsbank.module.tapi.grpc.common.TimestampOrBuilder getStatusTimestampOrBuilder();

  /**
   * <pre>
   ** Validity date of the order
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Date validity_date = 11;</code>
   */
  boolean hasValidityDate();
  /**
   * <pre>
   ** Validity date of the order
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Date validity_date = 11;</code>
   */
  com.consorsbank.module.tapi.grpc.common.Date getValidityDate();
  /**
   * <pre>
   ** Validity date of the order
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Date validity_date = 11;</code>
   */
  com.consorsbank.module.tapi.grpc.common.DateOrBuilder getValidityDateOrBuilder();

  /**
   * <pre>
   ** 
   * Limit value. Used as the order limit for all Limit order model with exception of the 
   * StopLimit order model. For this order model please use stop limit field. 
   * </pre>
   *
   * <code>double limit = 12;</code>
   */
  double getLimit();

  /**
   * <pre>
   ** 
   * Stop value. This value can be used only together with StopMarket, StopLimit and OneCancelOter order models. 
   * </pre>
   *
   * <code>double stop = 13;</code>
   */
  double getStop();

  /**
   * <pre>
   ** 
   * Stop limit value
   * Can be used only tigether with the StopLimit order model.
   * The meaning of the value is limit of the order after stop.
   *  
   * </pre>
   *
   * <code>double stop_limit = 14;</code>
   */
  double getStopLimit();

  /**
   * <pre>
   ** Traling distance in traling notation units or empty value 
   * </pre>
   *
   * <code>double trailing_distance = 15;</code>
   */
  double getTrailingDistance();

  /**
   * <pre>
   ** Trailing notation for the trailing orders 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TrailingNotation trailing_notation = 16;</code>
   */
  int getTrailingNotationValue();
  /**
   * <pre>
   ** Trailing notation for the trailing orders 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TrailingNotation trailing_notation = 16;</code>
   */
  com.consorsbank.module.tapi.grpc.trading.TrailingNotation getTrailingNotation();

  /**
   * <pre>
   ** Trailing limit tolerance for the trailing orders 
   * </pre>
   *
   * <code>double trailing_limit_tolerance = 17;</code>
   */
  double getTrailingLimitTolerance();

  /**
   * <pre>
   ** Dripping quantity #pro# only 
   * </pre>
   *
   * <code>double dripping_quantity = 18;</code>
   */
  double getDrippingQuantity();

  /**
   * <pre>
   ** Trading partner name 
   * </pre>
   *
   * <code>string trading_partner_name = 19;</code>
   */
  java.lang.String getTradingPartnerName();
  /**
   * <pre>
   ** Trading partner name 
   * </pre>
   *
   * <code>string trading_partner_name = 19;</code>
   */
  com.google.protobuf.ByteString
      getTradingPartnerNameBytes();

  /**
   * <pre>
   ** Execution quote for the executed amount 
   * </pre>
   *
   * <code>double execution_quote = 20;</code>
   */
  double getExecutionQuote();

  /**
   * <pre>
   **
   * Unique id of the order. Used for the order matching.
   * In the #pro# version of the ActiveTrader order_number can be changed after activation / deactivation.
   * All order activities need actual or delivered form the system order_number. 
   * Typical scenario is to map and update unique id to the order number delivered from the API.    
   * </pre>
   *
   * <code>string unique_id = 21;</code>
   */
  java.lang.String getUniqueId();
  /**
   * <pre>
   **
   * Unique id of the order. Used for the order matching.
   * In the #pro# version of the ActiveTrader order_number can be changed after activation / deactivation.
   * All order activities need actual or delivered form the system order_number. 
   * Typical scenario is to map and update unique id to the order number delivered from the API.    
   * </pre>
   *
   * <code>string unique_id = 21;</code>
   */
  com.google.protobuf.ByteString
      getUniqueIdBytes();
}
