// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package com.consorsbank.module.tapi.grpc.order;

/**
 * <pre>
 **
 * Order reply represents result of the add order or accept quote requests
 * </pre>
 *
 * Protobuf type {@code com.consorsbank.module.tapi.grpc.OrderReply}
 */
public  final class OrderReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.consorsbank.module.tapi.grpc.OrderReply)
    OrderReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderReply.newBuilder() to construct.
  private OrderReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderReply() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder subBuilder = null;
            if (account_ != null) {
              subBuilder = account_.toBuilder();
            }
            account_ = input.readMessage(com.consorsbank.module.tapi.grpc.account.TradingAccount.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(account_);
              account_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.consorsbank.module.tapi.grpc.order.Order.Builder subBuilder = null;
            if (order_ != null) {
              subBuilder = order_.toBuilder();
            }
            order_ = input.readMessage(com.consorsbank.module.tapi.grpc.order.Order.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(order_);
              order_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.consorsbank.module.tapi.grpc.order.OrderCosts.Builder subBuilder = null;
            if (orderCosts_ != null) {
              subBuilder = orderCosts_.toBuilder();
            }
            orderCosts_ = input.readMessage(com.consorsbank.module.tapi.grpc.order.OrderCosts.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(orderCosts_);
              orderCosts_ = subBuilder.buildPartial();
            }

            break;
          }
          case 8002: {
            com.consorsbank.module.tapi.grpc.common.Error.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.consorsbank.module.tapi.grpc.common.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_OrderReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_OrderReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.consorsbank.module.tapi.grpc.order.OrderReply.class, com.consorsbank.module.tapi.grpc.order.OrderReply.Builder.class);
  }

  public static final int ACCOUNT_FIELD_NUMBER = 1;
  private com.consorsbank.module.tapi.grpc.account.TradingAccount account_;
  /**
   * <pre>
   ** Trading account 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  public boolean hasAccount() {
    return account_ != null;
  }
  /**
   * <pre>
   ** Trading account 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  public com.consorsbank.module.tapi.grpc.account.TradingAccount getAccount() {
    return account_ == null ? com.consorsbank.module.tapi.grpc.account.TradingAccount.getDefaultInstance() : account_;
  }
  /**
   * <pre>
   ** Trading account 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
   */
  public com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder getAccountOrBuilder() {
    return getAccount();
  }

  public static final int ORDER_FIELD_NUMBER = 2;
  private com.consorsbank.module.tapi.grpc.order.Order order_;
  /**
   * <pre>
   ** Result order 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
   */
  public boolean hasOrder() {
    return order_ != null;
  }
  /**
   * <pre>
   ** Result order 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
   */
  public com.consorsbank.module.tapi.grpc.order.Order getOrder() {
    return order_ == null ? com.consorsbank.module.tapi.grpc.order.Order.getDefaultInstance() : order_;
  }
  /**
   * <pre>
   ** Result order 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
   */
  public com.consorsbank.module.tapi.grpc.order.OrderOrBuilder getOrderOrBuilder() {
    return getOrder();
  }

  public static final int ORDER_COSTS_FIELD_NUMBER = 3;
  private com.consorsbank.module.tapi.grpc.order.OrderCosts orderCosts_;
  /**
   * <pre>
   **
   * Order costs. This field contains data if order costs are requested
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
   */
  public boolean hasOrderCosts() {
    return orderCosts_ != null;
  }
  /**
   * <pre>
   **
   * Order costs. This field contains data if order costs are requested
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
   */
  public com.consorsbank.module.tapi.grpc.order.OrderCosts getOrderCosts() {
    return orderCosts_ == null ? com.consorsbank.module.tapi.grpc.order.OrderCosts.getDefaultInstance() : orderCosts_;
  }
  /**
   * <pre>
   **
   * Order costs. This field contains data if order costs are requested
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
   */
  public com.consorsbank.module.tapi.grpc.order.OrderCostsOrBuilder getOrderCostsOrBuilder() {
    return getOrderCosts();
  }

  public static final int ERROR_FIELD_NUMBER = 1000;
  private com.consorsbank.module.tapi.grpc.common.Error error_;
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  public com.consorsbank.module.tapi.grpc.common.Error getError() {
    return error_ == null ? com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
  }
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  public com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (account_ != null) {
      output.writeMessage(1, getAccount());
    }
    if (order_ != null) {
      output.writeMessage(2, getOrder());
    }
    if (orderCosts_ != null) {
      output.writeMessage(3, getOrderCosts());
    }
    if (error_ != null) {
      output.writeMessage(1000, getError());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (account_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAccount());
    }
    if (order_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOrder());
    }
    if (orderCosts_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getOrderCosts());
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1000, getError());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.consorsbank.module.tapi.grpc.order.OrderReply)) {
      return super.equals(obj);
    }
    com.consorsbank.module.tapi.grpc.order.OrderReply other = (com.consorsbank.module.tapi.grpc.order.OrderReply) obj;

    boolean result = true;
    result = result && (hasAccount() == other.hasAccount());
    if (hasAccount()) {
      result = result && getAccount()
          .equals(other.getAccount());
    }
    result = result && (hasOrder() == other.hasOrder());
    if (hasOrder()) {
      result = result && getOrder()
          .equals(other.getOrder());
    }
    result = result && (hasOrderCosts() == other.hasOrderCosts());
    if (hasOrderCosts()) {
      result = result && getOrderCosts()
          .equals(other.getOrderCosts());
    }
    result = result && (hasError() == other.hasError());
    if (hasError()) {
      result = result && getError()
          .equals(other.getError());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAccount()) {
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
    }
    if (hasOrder()) {
      hash = (37 * hash) + ORDER_FIELD_NUMBER;
      hash = (53 * hash) + getOrder().hashCode();
    }
    if (hasOrderCosts()) {
      hash = (37 * hash) + ORDER_COSTS_FIELD_NUMBER;
      hash = (53 * hash) + getOrderCosts().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.order.OrderReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.consorsbank.module.tapi.grpc.order.OrderReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Order reply represents result of the add order or accept quote requests
   * </pre>
   *
   * Protobuf type {@code com.consorsbank.module.tapi.grpc.OrderReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.consorsbank.module.tapi.grpc.OrderReply)
      com.consorsbank.module.tapi.grpc.order.OrderReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_OrderReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_OrderReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.consorsbank.module.tapi.grpc.order.OrderReply.class, com.consorsbank.module.tapi.grpc.order.OrderReply.Builder.class);
    }

    // Construct using com.consorsbank.module.tapi.grpc.order.OrderReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (accountBuilder_ == null) {
        account_ = null;
      } else {
        account_ = null;
        accountBuilder_ = null;
      }
      if (orderBuilder_ == null) {
        order_ = null;
      } else {
        order_ = null;
        orderBuilder_ = null;
      }
      if (orderCostsBuilder_ == null) {
        orderCosts_ = null;
      } else {
        orderCosts_ = null;
        orderCostsBuilder_ = null;
      }
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_OrderReply_descriptor;
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.order.OrderReply getDefaultInstanceForType() {
      return com.consorsbank.module.tapi.grpc.order.OrderReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.order.OrderReply build() {
      com.consorsbank.module.tapi.grpc.order.OrderReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.order.OrderReply buildPartial() {
      com.consorsbank.module.tapi.grpc.order.OrderReply result = new com.consorsbank.module.tapi.grpc.order.OrderReply(this);
      if (accountBuilder_ == null) {
        result.account_ = account_;
      } else {
        result.account_ = accountBuilder_.build();
      }
      if (orderBuilder_ == null) {
        result.order_ = order_;
      } else {
        result.order_ = orderBuilder_.build();
      }
      if (orderCostsBuilder_ == null) {
        result.orderCosts_ = orderCosts_;
      } else {
        result.orderCosts_ = orderCostsBuilder_.build();
      }
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.consorsbank.module.tapi.grpc.order.OrderReply) {
        return mergeFrom((com.consorsbank.module.tapi.grpc.order.OrderReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.consorsbank.module.tapi.grpc.order.OrderReply other) {
      if (other == com.consorsbank.module.tapi.grpc.order.OrderReply.getDefaultInstance()) return this;
      if (other.hasAccount()) {
        mergeAccount(other.getAccount());
      }
      if (other.hasOrder()) {
        mergeOrder(other.getOrder());
      }
      if (other.hasOrderCosts()) {
        mergeOrderCosts(other.getOrderCosts());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.consorsbank.module.tapi.grpc.order.OrderReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.consorsbank.module.tapi.grpc.order.OrderReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.consorsbank.module.tapi.grpc.account.TradingAccount account_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.account.TradingAccount, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder, com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder> accountBuilder_;
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public boolean hasAccount() {
      return accountBuilder_ != null || account_ != null;
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccount getAccount() {
      if (accountBuilder_ == null) {
        return account_ == null ? com.consorsbank.module.tapi.grpc.account.TradingAccount.getDefaultInstance() : account_;
      } else {
        return accountBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public Builder setAccount(com.consorsbank.module.tapi.grpc.account.TradingAccount value) {
      if (accountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        account_ = value;
        onChanged();
      } else {
        accountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public Builder setAccount(
        com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder builderForValue) {
      if (accountBuilder_ == null) {
        account_ = builderForValue.build();
        onChanged();
      } else {
        accountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public Builder mergeAccount(com.consorsbank.module.tapi.grpc.account.TradingAccount value) {
      if (accountBuilder_ == null) {
        if (account_ != null) {
          account_ =
            com.consorsbank.module.tapi.grpc.account.TradingAccount.newBuilder(account_).mergeFrom(value).buildPartial();
        } else {
          account_ = value;
        }
        onChanged();
      } else {
        accountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public Builder clearAccount() {
      if (accountBuilder_ == null) {
        account_ = null;
        onChanged();
      } else {
        account_ = null;
        accountBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder getAccountBuilder() {
      
      onChanged();
      return getAccountFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder getAccountOrBuilder() {
      if (accountBuilder_ != null) {
        return accountBuilder_.getMessageOrBuilder();
      } else {
        return account_ == null ?
            com.consorsbank.module.tapi.grpc.account.TradingAccount.getDefaultInstance() : account_;
      }
    }
    /**
     * <pre>
     ** Trading account 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.TradingAccount account = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.account.TradingAccount, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder, com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder> 
        getAccountFieldBuilder() {
      if (accountBuilder_ == null) {
        accountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.account.TradingAccount, com.consorsbank.module.tapi.grpc.account.TradingAccount.Builder, com.consorsbank.module.tapi.grpc.account.TradingAccountOrBuilder>(
                getAccount(),
                getParentForChildren(),
                isClean());
        account_ = null;
      }
      return accountBuilder_;
    }

    private com.consorsbank.module.tapi.grpc.order.Order order_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.order.Order, com.consorsbank.module.tapi.grpc.order.Order.Builder, com.consorsbank.module.tapi.grpc.order.OrderOrBuilder> orderBuilder_;
    /**
     * <pre>
     ** Result order 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
     */
    public boolean hasOrder() {
      return orderBuilder_ != null || order_ != null;
    }
    /**
     * <pre>
     ** Result order 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.Order getOrder() {
      if (orderBuilder_ == null) {
        return order_ == null ? com.consorsbank.module.tapi.grpc.order.Order.getDefaultInstance() : order_;
      } else {
        return orderBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     ** Result order 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
     */
    public Builder setOrder(com.consorsbank.module.tapi.grpc.order.Order value) {
      if (orderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        order_ = value;
        onChanged();
      } else {
        orderBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     ** Result order 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
     */
    public Builder setOrder(
        com.consorsbank.module.tapi.grpc.order.Order.Builder builderForValue) {
      if (orderBuilder_ == null) {
        order_ = builderForValue.build();
        onChanged();
      } else {
        orderBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     ** Result order 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
     */
    public Builder mergeOrder(com.consorsbank.module.tapi.grpc.order.Order value) {
      if (orderBuilder_ == null) {
        if (order_ != null) {
          order_ =
            com.consorsbank.module.tapi.grpc.order.Order.newBuilder(order_).mergeFrom(value).buildPartial();
        } else {
          order_ = value;
        }
        onChanged();
      } else {
        orderBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     ** Result order 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
     */
    public Builder clearOrder() {
      if (orderBuilder_ == null) {
        order_ = null;
        onChanged();
      } else {
        order_ = null;
        orderBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     ** Result order 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.Order.Builder getOrderBuilder() {
      
      onChanged();
      return getOrderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     ** Result order 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.OrderOrBuilder getOrderOrBuilder() {
      if (orderBuilder_ != null) {
        return orderBuilder_.getMessageOrBuilder();
      } else {
        return order_ == null ?
            com.consorsbank.module.tapi.grpc.order.Order.getDefaultInstance() : order_;
      }
    }
    /**
     * <pre>
     ** Result order 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Order order = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.order.Order, com.consorsbank.module.tapi.grpc.order.Order.Builder, com.consorsbank.module.tapi.grpc.order.OrderOrBuilder> 
        getOrderFieldBuilder() {
      if (orderBuilder_ == null) {
        orderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.order.Order, com.consorsbank.module.tapi.grpc.order.Order.Builder, com.consorsbank.module.tapi.grpc.order.OrderOrBuilder>(
                getOrder(),
                getParentForChildren(),
                isClean());
        order_ = null;
      }
      return orderBuilder_;
    }

    private com.consorsbank.module.tapi.grpc.order.OrderCosts orderCosts_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.order.OrderCosts, com.consorsbank.module.tapi.grpc.order.OrderCosts.Builder, com.consorsbank.module.tapi.grpc.order.OrderCostsOrBuilder> orderCostsBuilder_;
    /**
     * <pre>
     **
     * Order costs. This field contains data if order costs are requested
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
     */
    public boolean hasOrderCosts() {
      return orderCostsBuilder_ != null || orderCosts_ != null;
    }
    /**
     * <pre>
     **
     * Order costs. This field contains data if order costs are requested
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.OrderCosts getOrderCosts() {
      if (orderCostsBuilder_ == null) {
        return orderCosts_ == null ? com.consorsbank.module.tapi.grpc.order.OrderCosts.getDefaultInstance() : orderCosts_;
      } else {
        return orderCostsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * Order costs. This field contains data if order costs are requested
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
     */
    public Builder setOrderCosts(com.consorsbank.module.tapi.grpc.order.OrderCosts value) {
      if (orderCostsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        orderCosts_ = value;
        onChanged();
      } else {
        orderCostsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Order costs. This field contains data if order costs are requested
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
     */
    public Builder setOrderCosts(
        com.consorsbank.module.tapi.grpc.order.OrderCosts.Builder builderForValue) {
      if (orderCostsBuilder_ == null) {
        orderCosts_ = builderForValue.build();
        onChanged();
      } else {
        orderCostsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * Order costs. This field contains data if order costs are requested
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
     */
    public Builder mergeOrderCosts(com.consorsbank.module.tapi.grpc.order.OrderCosts value) {
      if (orderCostsBuilder_ == null) {
        if (orderCosts_ != null) {
          orderCosts_ =
            com.consorsbank.module.tapi.grpc.order.OrderCosts.newBuilder(orderCosts_).mergeFrom(value).buildPartial();
        } else {
          orderCosts_ = value;
        }
        onChanged();
      } else {
        orderCostsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Order costs. This field contains data if order costs are requested
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
     */
    public Builder clearOrderCosts() {
      if (orderCostsBuilder_ == null) {
        orderCosts_ = null;
        onChanged();
      } else {
        orderCosts_ = null;
        orderCostsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * Order costs. This field contains data if order costs are requested
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.OrderCosts.Builder getOrderCostsBuilder() {
      
      onChanged();
      return getOrderCostsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * Order costs. This field contains data if order costs are requested
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.OrderCostsOrBuilder getOrderCostsOrBuilder() {
      if (orderCostsBuilder_ != null) {
        return orderCostsBuilder_.getMessageOrBuilder();
      } else {
        return orderCosts_ == null ?
            com.consorsbank.module.tapi.grpc.order.OrderCosts.getDefaultInstance() : orderCosts_;
      }
    }
    /**
     * <pre>
     **
     * Order costs. This field contains data if order costs are requested
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderCosts order_costs = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.order.OrderCosts, com.consorsbank.module.tapi.grpc.order.OrderCosts.Builder, com.consorsbank.module.tapi.grpc.order.OrderCostsOrBuilder> 
        getOrderCostsFieldBuilder() {
      if (orderCostsBuilder_ == null) {
        orderCostsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.order.OrderCosts, com.consorsbank.module.tapi.grpc.order.OrderCosts.Builder, com.consorsbank.module.tapi.grpc.order.OrderCostsOrBuilder>(
                getOrderCosts(),
                getParentForChildren(),
                isClean());
        orderCosts_ = null;
      }
      return orderCostsBuilder_;
    }

    private com.consorsbank.module.tapi.grpc.common.Error error_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder> errorBuilder_;
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder setError(com.consorsbank.module.tapi.grpc.common.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder setError(
        com.consorsbank.module.tapi.grpc.common.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder mergeError(com.consorsbank.module.tapi.grpc.common.Error value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.consorsbank.module.tapi.grpc.common.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.Error.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.consorsbank.module.tapi.grpc.OrderReply)
  }

  // @@protoc_insertion_point(class_scope:com.consorsbank.module.tapi.grpc.OrderReply)
  private static final com.consorsbank.module.tapi.grpc.order.OrderReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.consorsbank.module.tapi.grpc.order.OrderReply();
  }

  public static com.consorsbank.module.tapi.grpc.order.OrderReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderReply>
      PARSER = new com.google.protobuf.AbstractParser<OrderReply>() {
    @java.lang.Override
    public OrderReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.consorsbank.module.tapi.grpc.order.OrderReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

