// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package com.consorsbank.module.tapi.grpc.order;

/**
 * <pre>
 **
 * Quote reply represents data with quote answers from requested markets 
 * </pre>
 *
 * Protobuf type {@code com.consorsbank.module.tapi.grpc.QuoteReply}
 */
public  final class QuoteReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.consorsbank.module.tapi.grpc.QuoteReply)
    QuoteReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QuoteReply.newBuilder() to construct.
  private QuoteReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuoteReply() {
    orderType_ = 0;
    priceEntries_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QuoteReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder subBuilder = null;
            if (securityCode_ != null) {
              subBuilder = securityCode_.toBuilder();
            }
            securityCode_ = input.readMessage(com.consorsbank.module.tapi.grpc.security.SecurityCode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(securityCode_);
              securityCode_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            orderType_ = rawValue;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              priceEntries_ = new java.util.ArrayList<com.consorsbank.module.tapi.grpc.order.QuoteEntry>();
              mutable_bitField0_ |= 0x00000004;
            }
            priceEntries_.add(
                input.readMessage(com.consorsbank.module.tapi.grpc.order.QuoteEntry.parser(), extensionRegistry));
            break;
          }
          case 8002: {
            com.consorsbank.module.tapi.grpc.common.Error.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.consorsbank.module.tapi.grpc.common.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        priceEntries_ = java.util.Collections.unmodifiableList(priceEntries_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_QuoteReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_QuoteReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.consorsbank.module.tapi.grpc.order.QuoteReply.class, com.consorsbank.module.tapi.grpc.order.QuoteReply.Builder.class);
  }

  private int bitField0_;
  public static final int SECURITY_CODE_FIELD_NUMBER = 1;
  private com.consorsbank.module.tapi.grpc.security.SecurityCode securityCode_;
  /**
   * <pre>
   ** Security code 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
   */
  public boolean hasSecurityCode() {
    return securityCode_ != null;
  }
  /**
   * <pre>
   ** Security code 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
   */
  public com.consorsbank.module.tapi.grpc.security.SecurityCode getSecurityCode() {
    return securityCode_ == null ? com.consorsbank.module.tapi.grpc.security.SecurityCode.getDefaultInstance() : securityCode_;
  }
  /**
   * <pre>
   ** Security code 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
   */
  public com.consorsbank.module.tapi.grpc.security.SecurityCodeOrBuilder getSecurityCodeOrBuilder() {
    return getSecurityCode();
  }

  public static final int ORDER_TYPE_FIELD_NUMBER = 2;
  private int orderType_;
  /**
   * <pre>
   ** Order type 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 2;</code>
   */
  public int getOrderTypeValue() {
    return orderType_;
  }
  /**
   * <pre>
   ** Order type 
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 2;</code>
   */
  public com.consorsbank.module.tapi.grpc.trading.OrderType getOrderType() {
    @SuppressWarnings("deprecation")
    com.consorsbank.module.tapi.grpc.trading.OrderType result = com.consorsbank.module.tapi.grpc.trading.OrderType.valueOf(orderType_);
    return result == null ? com.consorsbank.module.tapi.grpc.trading.OrderType.UNRECOGNIZED : result;
  }

  public static final int PRICE_ENTRIES_FIELD_NUMBER = 3;
  private java.util.List<com.consorsbank.module.tapi.grpc.order.QuoteEntry> priceEntries_;
  /**
   * <pre>
   ** List of the quites 
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
   */
  public java.util.List<com.consorsbank.module.tapi.grpc.order.QuoteEntry> getPriceEntriesList() {
    return priceEntries_;
  }
  /**
   * <pre>
   ** List of the quites 
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
   */
  public java.util.List<? extends com.consorsbank.module.tapi.grpc.order.QuoteEntryOrBuilder> 
      getPriceEntriesOrBuilderList() {
    return priceEntries_;
  }
  /**
   * <pre>
   ** List of the quites 
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
   */
  public int getPriceEntriesCount() {
    return priceEntries_.size();
  }
  /**
   * <pre>
   ** List of the quites 
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
   */
  public com.consorsbank.module.tapi.grpc.order.QuoteEntry getPriceEntries(int index) {
    return priceEntries_.get(index);
  }
  /**
   * <pre>
   ** List of the quites 
   * </pre>
   *
   * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
   */
  public com.consorsbank.module.tapi.grpc.order.QuoteEntryOrBuilder getPriceEntriesOrBuilder(
      int index) {
    return priceEntries_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 1000;
  private com.consorsbank.module.tapi.grpc.common.Error error_;
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  public com.consorsbank.module.tapi.grpc.common.Error getError() {
    return error_ == null ? com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
  }
  /**
   * <pre>
   **
   * Error information if occuirs
   * </pre>
   *
   * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
   */
  public com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (securityCode_ != null) {
      output.writeMessage(1, getSecurityCode());
    }
    if (orderType_ != com.consorsbank.module.tapi.grpc.trading.OrderType.NO_ORDER_TYPE.getNumber()) {
      output.writeEnum(2, orderType_);
    }
    for (int i = 0; i < priceEntries_.size(); i++) {
      output.writeMessage(3, priceEntries_.get(i));
    }
    if (error_ != null) {
      output.writeMessage(1000, getError());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (securityCode_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSecurityCode());
    }
    if (orderType_ != com.consorsbank.module.tapi.grpc.trading.OrderType.NO_ORDER_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, orderType_);
    }
    for (int i = 0; i < priceEntries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, priceEntries_.get(i));
    }
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1000, getError());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.consorsbank.module.tapi.grpc.order.QuoteReply)) {
      return super.equals(obj);
    }
    com.consorsbank.module.tapi.grpc.order.QuoteReply other = (com.consorsbank.module.tapi.grpc.order.QuoteReply) obj;

    boolean result = true;
    result = result && (hasSecurityCode() == other.hasSecurityCode());
    if (hasSecurityCode()) {
      result = result && getSecurityCode()
          .equals(other.getSecurityCode());
    }
    result = result && orderType_ == other.orderType_;
    result = result && getPriceEntriesList()
        .equals(other.getPriceEntriesList());
    result = result && (hasError() == other.hasError());
    if (hasError()) {
      result = result && getError()
          .equals(other.getError());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSecurityCode()) {
      hash = (37 * hash) + SECURITY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityCode().hashCode();
    }
    hash = (37 * hash) + ORDER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + orderType_;
    if (getPriceEntriesCount() > 0) {
      hash = (37 * hash) + PRICE_ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getPriceEntriesList().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.consorsbank.module.tapi.grpc.order.QuoteReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.consorsbank.module.tapi.grpc.order.QuoteReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Quote reply represents data with quote answers from requested markets 
   * </pre>
   *
   * Protobuf type {@code com.consorsbank.module.tapi.grpc.QuoteReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.consorsbank.module.tapi.grpc.QuoteReply)
      com.consorsbank.module.tapi.grpc.order.QuoteReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_QuoteReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_QuoteReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.consorsbank.module.tapi.grpc.order.QuoteReply.class, com.consorsbank.module.tapi.grpc.order.QuoteReply.Builder.class);
    }

    // Construct using com.consorsbank.module.tapi.grpc.order.QuoteReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPriceEntriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (securityCodeBuilder_ == null) {
        securityCode_ = null;
      } else {
        securityCode_ = null;
        securityCodeBuilder_ = null;
      }
      orderType_ = 0;

      if (priceEntriesBuilder_ == null) {
        priceEntries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        priceEntriesBuilder_.clear();
      }
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.consorsbank.module.tapi.grpc.order.OrderService.internal_static_com_consorsbank_module_tapi_grpc_QuoteReply_descriptor;
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.order.QuoteReply getDefaultInstanceForType() {
      return com.consorsbank.module.tapi.grpc.order.QuoteReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.order.QuoteReply build() {
      com.consorsbank.module.tapi.grpc.order.QuoteReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.consorsbank.module.tapi.grpc.order.QuoteReply buildPartial() {
      com.consorsbank.module.tapi.grpc.order.QuoteReply result = new com.consorsbank.module.tapi.grpc.order.QuoteReply(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (securityCodeBuilder_ == null) {
        result.securityCode_ = securityCode_;
      } else {
        result.securityCode_ = securityCodeBuilder_.build();
      }
      result.orderType_ = orderType_;
      if (priceEntriesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          priceEntries_ = java.util.Collections.unmodifiableList(priceEntries_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.priceEntries_ = priceEntries_;
      } else {
        result.priceEntries_ = priceEntriesBuilder_.build();
      }
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.consorsbank.module.tapi.grpc.order.QuoteReply) {
        return mergeFrom((com.consorsbank.module.tapi.grpc.order.QuoteReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.consorsbank.module.tapi.grpc.order.QuoteReply other) {
      if (other == com.consorsbank.module.tapi.grpc.order.QuoteReply.getDefaultInstance()) return this;
      if (other.hasSecurityCode()) {
        mergeSecurityCode(other.getSecurityCode());
      }
      if (other.orderType_ != 0) {
        setOrderTypeValue(other.getOrderTypeValue());
      }
      if (priceEntriesBuilder_ == null) {
        if (!other.priceEntries_.isEmpty()) {
          if (priceEntries_.isEmpty()) {
            priceEntries_ = other.priceEntries_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePriceEntriesIsMutable();
            priceEntries_.addAll(other.priceEntries_);
          }
          onChanged();
        }
      } else {
        if (!other.priceEntries_.isEmpty()) {
          if (priceEntriesBuilder_.isEmpty()) {
            priceEntriesBuilder_.dispose();
            priceEntriesBuilder_ = null;
            priceEntries_ = other.priceEntries_;
            bitField0_ = (bitField0_ & ~0x00000004);
            priceEntriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPriceEntriesFieldBuilder() : null;
          } else {
            priceEntriesBuilder_.addAllMessages(other.priceEntries_);
          }
        }
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.consorsbank.module.tapi.grpc.order.QuoteReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.consorsbank.module.tapi.grpc.order.QuoteReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.consorsbank.module.tapi.grpc.security.SecurityCode securityCode_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.security.SecurityCode, com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder, com.consorsbank.module.tapi.grpc.security.SecurityCodeOrBuilder> securityCodeBuilder_;
    /**
     * <pre>
     ** Security code 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
     */
    public boolean hasSecurityCode() {
      return securityCodeBuilder_ != null || securityCode_ != null;
    }
    /**
     * <pre>
     ** Security code 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.security.SecurityCode getSecurityCode() {
      if (securityCodeBuilder_ == null) {
        return securityCode_ == null ? com.consorsbank.module.tapi.grpc.security.SecurityCode.getDefaultInstance() : securityCode_;
      } else {
        return securityCodeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     ** Security code 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
     */
    public Builder setSecurityCode(com.consorsbank.module.tapi.grpc.security.SecurityCode value) {
      if (securityCodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        securityCode_ = value;
        onChanged();
      } else {
        securityCodeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     ** Security code 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
     */
    public Builder setSecurityCode(
        com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder builderForValue) {
      if (securityCodeBuilder_ == null) {
        securityCode_ = builderForValue.build();
        onChanged();
      } else {
        securityCodeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     ** Security code 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
     */
    public Builder mergeSecurityCode(com.consorsbank.module.tapi.grpc.security.SecurityCode value) {
      if (securityCodeBuilder_ == null) {
        if (securityCode_ != null) {
          securityCode_ =
            com.consorsbank.module.tapi.grpc.security.SecurityCode.newBuilder(securityCode_).mergeFrom(value).buildPartial();
        } else {
          securityCode_ = value;
        }
        onChanged();
      } else {
        securityCodeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     ** Security code 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
     */
    public Builder clearSecurityCode() {
      if (securityCodeBuilder_ == null) {
        securityCode_ = null;
        onChanged();
      } else {
        securityCode_ = null;
        securityCodeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     ** Security code 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder getSecurityCodeBuilder() {
      
      onChanged();
      return getSecurityCodeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     ** Security code 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
     */
    public com.consorsbank.module.tapi.grpc.security.SecurityCodeOrBuilder getSecurityCodeOrBuilder() {
      if (securityCodeBuilder_ != null) {
        return securityCodeBuilder_.getMessageOrBuilder();
      } else {
        return securityCode_ == null ?
            com.consorsbank.module.tapi.grpc.security.SecurityCode.getDefaultInstance() : securityCode_;
      }
    }
    /**
     * <pre>
     ** Security code 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.SecurityCode security_code = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.security.SecurityCode, com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder, com.consorsbank.module.tapi.grpc.security.SecurityCodeOrBuilder> 
        getSecurityCodeFieldBuilder() {
      if (securityCodeBuilder_ == null) {
        securityCodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.security.SecurityCode, com.consorsbank.module.tapi.grpc.security.SecurityCode.Builder, com.consorsbank.module.tapi.grpc.security.SecurityCodeOrBuilder>(
                getSecurityCode(),
                getParentForChildren(),
                isClean());
        securityCode_ = null;
      }
      return securityCodeBuilder_;
    }

    private int orderType_ = 0;
    /**
     * <pre>
     ** Order type 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 2;</code>
     */
    public int getOrderTypeValue() {
      return orderType_;
    }
    /**
     * <pre>
     ** Order type 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 2;</code>
     */
    public Builder setOrderTypeValue(int value) {
      orderType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     ** Order type 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 2;</code>
     */
    public com.consorsbank.module.tapi.grpc.trading.OrderType getOrderType() {
      @SuppressWarnings("deprecation")
      com.consorsbank.module.tapi.grpc.trading.OrderType result = com.consorsbank.module.tapi.grpc.trading.OrderType.valueOf(orderType_);
      return result == null ? com.consorsbank.module.tapi.grpc.trading.OrderType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     ** Order type 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 2;</code>
     */
    public Builder setOrderType(com.consorsbank.module.tapi.grpc.trading.OrderType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      orderType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     ** Order type 
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.OrderType order_type = 2;</code>
     */
    public Builder clearOrderType() {
      
      orderType_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.consorsbank.module.tapi.grpc.order.QuoteEntry> priceEntries_ =
      java.util.Collections.emptyList();
    private void ensurePriceEntriesIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        priceEntries_ = new java.util.ArrayList<com.consorsbank.module.tapi.grpc.order.QuoteEntry>(priceEntries_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.order.QuoteEntry, com.consorsbank.module.tapi.grpc.order.QuoteEntry.Builder, com.consorsbank.module.tapi.grpc.order.QuoteEntryOrBuilder> priceEntriesBuilder_;

    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public java.util.List<com.consorsbank.module.tapi.grpc.order.QuoteEntry> getPriceEntriesList() {
      if (priceEntriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(priceEntries_);
      } else {
        return priceEntriesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public int getPriceEntriesCount() {
      if (priceEntriesBuilder_ == null) {
        return priceEntries_.size();
      } else {
        return priceEntriesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.QuoteEntry getPriceEntries(int index) {
      if (priceEntriesBuilder_ == null) {
        return priceEntries_.get(index);
      } else {
        return priceEntriesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public Builder setPriceEntries(
        int index, com.consorsbank.module.tapi.grpc.order.QuoteEntry value) {
      if (priceEntriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePriceEntriesIsMutable();
        priceEntries_.set(index, value);
        onChanged();
      } else {
        priceEntriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public Builder setPriceEntries(
        int index, com.consorsbank.module.tapi.grpc.order.QuoteEntry.Builder builderForValue) {
      if (priceEntriesBuilder_ == null) {
        ensurePriceEntriesIsMutable();
        priceEntries_.set(index, builderForValue.build());
        onChanged();
      } else {
        priceEntriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public Builder addPriceEntries(com.consorsbank.module.tapi.grpc.order.QuoteEntry value) {
      if (priceEntriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePriceEntriesIsMutable();
        priceEntries_.add(value);
        onChanged();
      } else {
        priceEntriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public Builder addPriceEntries(
        int index, com.consorsbank.module.tapi.grpc.order.QuoteEntry value) {
      if (priceEntriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePriceEntriesIsMutable();
        priceEntries_.add(index, value);
        onChanged();
      } else {
        priceEntriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public Builder addPriceEntries(
        com.consorsbank.module.tapi.grpc.order.QuoteEntry.Builder builderForValue) {
      if (priceEntriesBuilder_ == null) {
        ensurePriceEntriesIsMutable();
        priceEntries_.add(builderForValue.build());
        onChanged();
      } else {
        priceEntriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public Builder addPriceEntries(
        int index, com.consorsbank.module.tapi.grpc.order.QuoteEntry.Builder builderForValue) {
      if (priceEntriesBuilder_ == null) {
        ensurePriceEntriesIsMutable();
        priceEntries_.add(index, builderForValue.build());
        onChanged();
      } else {
        priceEntriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public Builder addAllPriceEntries(
        java.lang.Iterable<? extends com.consorsbank.module.tapi.grpc.order.QuoteEntry> values) {
      if (priceEntriesBuilder_ == null) {
        ensurePriceEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, priceEntries_);
        onChanged();
      } else {
        priceEntriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public Builder clearPriceEntries() {
      if (priceEntriesBuilder_ == null) {
        priceEntries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        priceEntriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public Builder removePriceEntries(int index) {
      if (priceEntriesBuilder_ == null) {
        ensurePriceEntriesIsMutable();
        priceEntries_.remove(index);
        onChanged();
      } else {
        priceEntriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.QuoteEntry.Builder getPriceEntriesBuilder(
        int index) {
      return getPriceEntriesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.QuoteEntryOrBuilder getPriceEntriesOrBuilder(
        int index) {
      if (priceEntriesBuilder_ == null) {
        return priceEntries_.get(index);  } else {
        return priceEntriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public java.util.List<? extends com.consorsbank.module.tapi.grpc.order.QuoteEntryOrBuilder> 
         getPriceEntriesOrBuilderList() {
      if (priceEntriesBuilder_ != null) {
        return priceEntriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(priceEntries_);
      }
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.QuoteEntry.Builder addPriceEntriesBuilder() {
      return getPriceEntriesFieldBuilder().addBuilder(
          com.consorsbank.module.tapi.grpc.order.QuoteEntry.getDefaultInstance());
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public com.consorsbank.module.tapi.grpc.order.QuoteEntry.Builder addPriceEntriesBuilder(
        int index) {
      return getPriceEntriesFieldBuilder().addBuilder(
          index, com.consorsbank.module.tapi.grpc.order.QuoteEntry.getDefaultInstance());
    }
    /**
     * <pre>
     ** List of the quites 
     * </pre>
     *
     * <code>repeated .com.consorsbank.module.tapi.grpc.QuoteEntry price_entries = 3;</code>
     */
    public java.util.List<com.consorsbank.module.tapi.grpc.order.QuoteEntry.Builder> 
         getPriceEntriesBuilderList() {
      return getPriceEntriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.order.QuoteEntry, com.consorsbank.module.tapi.grpc.order.QuoteEntry.Builder, com.consorsbank.module.tapi.grpc.order.QuoteEntryOrBuilder> 
        getPriceEntriesFieldBuilder() {
      if (priceEntriesBuilder_ == null) {
        priceEntriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.order.QuoteEntry, com.consorsbank.module.tapi.grpc.order.QuoteEntry.Builder, com.consorsbank.module.tapi.grpc.order.QuoteEntryOrBuilder>(
                priceEntries_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        priceEntries_ = null;
      }
      return priceEntriesBuilder_;
    }

    private com.consorsbank.module.tapi.grpc.common.Error error_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder> errorBuilder_;
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.Error getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder setError(com.consorsbank.module.tapi.grpc.common.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder setError(
        com.consorsbank.module.tapi.grpc.common.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder mergeError(com.consorsbank.module.tapi.grpc.common.Error value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.consorsbank.module.tapi.grpc.common.Error.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.Error.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    public com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.consorsbank.module.tapi.grpc.common.Error.getDefaultInstance() : error_;
      }
    }
    /**
     * <pre>
     **
     * Error information if occuirs
     * </pre>
     *
     * <code>.com.consorsbank.module.tapi.grpc.Error error = 1000;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.consorsbank.module.tapi.grpc.common.Error, com.consorsbank.module.tapi.grpc.common.Error.Builder, com.consorsbank.module.tapi.grpc.common.ErrorOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.consorsbank.module.tapi.grpc.QuoteReply)
  }

  // @@protoc_insertion_point(class_scope:com.consorsbank.module.tapi.grpc.QuoteReply)
  private static final com.consorsbank.module.tapi.grpc.order.QuoteReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.consorsbank.module.tapi.grpc.order.QuoteReply();
  }

  public static com.consorsbank.module.tapi.grpc.order.QuoteReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuoteReply>
      PARSER = new com.google.protobuf.AbstractParser<QuoteReply>() {
    @java.lang.Override
    public QuoteReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QuoteReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QuoteReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QuoteReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.consorsbank.module.tapi.grpc.order.QuoteReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

