// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccessService.proto

package com.consorsbank.module.tapi.grpc.access;

public final class AccessService {
  private AccessService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_LoginReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_LoginReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_consorsbank_module_tapi_grpc_LogoutReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_consorsbank_module_tapi_grpc_LogoutReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023AccessService.proto\022 com.consorsbank.m" +
      "odule.tapi.grpc\032\014Common.proto\"\036\n\014LoginRe" +
      "quest\022\016\n\006secret\030\001 \001(\t\"[\n\nLoginReply\022\024\n\014a" +
      "ccess_token\030\001 \001(\t\0227\n\005error\030\350\007 \001(\0132\'.com." +
      "consorsbank.module.tapi.grpc.Error\"%\n\rLo" +
      "goutRequest\022\024\n\014access_token\030\001 \001(\t\"F\n\013Log" +
      "outReply\0227\n\005error\030\350\007 \001(\0132\'.com.consorsba" +
      "nk.module.tapi.grpc.ErrorB+\n\'com.consors" +
      "bank.module.tapi.grpc.accessP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.consorsbank.module.tapi.grpc.common.Common.getDescriptor(),
        }, assigner);
    internal_static_com_consorsbank_module_tapi_grpc_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_consorsbank_module_tapi_grpc_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_LoginRequest_descriptor,
        new java.lang.String[] { "Secret", });
    internal_static_com_consorsbank_module_tapi_grpc_LoginReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_consorsbank_module_tapi_grpc_LoginReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_LoginReply_descriptor,
        new java.lang.String[] { "AccessToken", "Error", });
    internal_static_com_consorsbank_module_tapi_grpc_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_consorsbank_module_tapi_grpc_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_LogoutRequest_descriptor,
        new java.lang.String[] { "AccessToken", });
    internal_static_com_consorsbank_module_tapi_grpc_LogoutReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_consorsbank_module_tapi_grpc_LogoutReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_consorsbank_module_tapi_grpc_LogoutReply_descriptor,
        new java.lang.String[] { "Error", });
    com.consorsbank.module.tapi.grpc.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
